import marimo

__generated_with = "0.13.15"
app = marimo.App()


@app.cell
def _():
    import marimo as mo

    return (mo,)


@app.cell
def _(mo):
    nav_menu = mo.nav_menu(
        {
            "/index.html": f"{mo.icon('lucide:home')} Home",
        },
        orientation="vertical",
    )
    nav_menu
    return


@app.cell
def _(mo):
    mo.md(r"""# Spring Semester Homework 1""")
    return


@app.cell
def _(mo):
    mo.md(
        r"""
    ## P61.7

    **Let $F$ be a field, $V = F^2$. We define an equivalence relation on $V - \lbrace 0 \rbrace$ by $v \sim w$ if and only if $v = \alpha w$ for some $\alpha \in F^{\times}$. The set of equivalence classes under this relation is called the one-dimensional projective space (or projective line) over $F$ and is denoted by $\mathbb{P}^1(F)$. We write elements of $V$ as column vectors, and the element of $\mathbb{P}^1(F)$ that is the equivalence class of $\begin{pmatrix} x \\ y \end{pmatrix}$ shall be written as $\begin{bmatrix} x\\y \end{bmatrix}$**.

    **Show that there is a well-defined action of $PSL(2, F)$ on $\mathbb{P}^1(F)$ given by** $$\overline{\begin{pmatrix} a&b \\ c&d \end{pmatrix}}\begin{bmatrix} x\\y \end{bmatrix} = \begin{bmatrix} ax+by\\cx+dy \end{bmatrix}$$ **and that this action is doubly transitive where $\overline{\begin{pmatrix} a&b \\ c&d \end{pmatrix}}$ denotes the image of $\begin{pmatrix} a&b \\ c&d \end{pmatrix} \in SL(2,F)$ in $PSL(2, F)$**.

    Proof

    Follow the axioms:

    1. If $\overline{\begin{pmatrix} a&b \\ c&d \end{pmatrix}} = 1 \in PSL(2,F)$ then $b = c = 0$ and $a = d$, so $\overline{\begin{pmatrix} a&b \\ c&d \end{pmatrix}}\begin{bmatrix} x\\y \end{bmatrix}$ $= \begin{bmatrix} ax\\ay \end{bmatrix}$ $= \begin{bmatrix} x\\y \end{bmatrix}$;
    2. $\overline{\begin{pmatrix} a'&b' \\ c'&d' \end{pmatrix}}(\overline{\begin{pmatrix} a&b \\ c&d \end{pmatrix}}\begin{bmatrix} x\\y \end{bmatrix})$ $=\overline{\begin{pmatrix} a'&b' \\ c'&d' \end{pmatrix}}\begin{bmatrix} ax+by\\cx+dy \end{bmatrix}$ $=\begin{bmatrix} a'(ax+by) + b'(cx+dy)\\c'(ax+by)+d'(cx+dy) \end{bmatrix}$, on the other hand $(\overline{\begin{pmatrix} a'&b' \\ c'&d' \end{pmatrix}}\overline{\begin{pmatrix} a&b \\ c&d \end{pmatrix}})\begin{bmatrix} x\\y \end{bmatrix}$ $=\overline{\begin{pmatrix} a'a+b'c&a'b+b'd \\ c'a+d'c&c'b+d'd \end{pmatrix}}\begin{bmatrix} x\\y \end{bmatrix}$ $=\begin{bmatrix} (a'a+b'c)x + (a'b+b'd)y\\(c'a+d'c)x+(c'b+d'd)y \end{bmatrix}$, so they are the same.

    (the point in part 2 is that the quotient image of product is the same as the product of quotient image, which is true since $G/N \times G/N \cong (G \times G)/(N \times N)$)

    For doubly transitivity, essentially for $\begin{bmatrix} x_1\\y_1 \end{bmatrix}\ne\begin{bmatrix} x_3\\y_3 \end{bmatrix},\begin{bmatrix} x_2\\y_2 \end{bmatrix}\ne\begin{bmatrix} x_4\\y_4 \end{bmatrix} \in\mathbb{P}^1(F)$ we want to find $\overline{\begin{pmatrix} a&b \\ c&d \end{pmatrix}}$ so that $\begin{cases} ax_1+by_1 = x_2 \\ cx_1 + dy_1 = y_2 \\ ax_3+by_3 = x_4 \\ cx_3+dy_3 = y_4 \end{cases}$. We can write this system as $\begin{pmatrix} x_1&y_1 \\ x_3&y_3 \end{pmatrix}\begin{pmatrix} a&c \\ b&d \end{pmatrix}=\begin{pmatrix} x_2&y_2 \\ x_4&y_4 \end{pmatrix}$. By assumption the determinant of $\begin{pmatrix} x_1&y_1 \\ x_3&y_3 \end{pmatrix}$ (and $\begin{pmatrix} x_2&y_2 \\ x_4&y_4 \end{pmatrix}$) is never $0$ so we always have a solution.

    The only problem is that if we directly solve this system and $\det{\begin{pmatrix} x_1&y_1 \\ x_3&y_3 \end{pmatrix}} \ne \det{\begin{pmatrix} x_2&y_2 \\ x_4&y_4 \end{pmatrix}}$ then $\det{\begin{pmatrix} a&b \\ c&d \end{pmatrix}} \ne 1$ (determinant of product is product of determinant) so it is in $PGL$ but not in $PSL$. In this case, say $\det{\begin{pmatrix} x_1&y_1 \\ x_3&y_3 \end{pmatrix}} = a \in F$ and $\det{\begin{pmatrix} x_2&y_2 \\ x_4&y_4 \end{pmatrix}} = b \in F$, with $a\ne b$, then $a^{-1}b \in F$ (it is not $0$ because a field does not have zero divisor). Replace $\begin{pmatrix} x_1\\y_1 \end{pmatrix}$ by $\begin{pmatrix} a^{-1}bx_1\\a^{-1}by_1 \end{pmatrix}$ so it is still in the same equivalence class, then the solution will necessarily be in $PSL$, thus we have double transitivity.

    ## P61.9

    **Let $F$ be the field of $7$ elements. For $0 \le i \le 6$ let $i$ represent $\begin{bmatrix}1 \\i  \end{bmatrix} \in \mathbb{P}^1(F)$; denote the remaining element $\begin{bmatrix}0\\1  \end{bmatrix}$ of $\mathbb{P}^1(F)$ by $\infty$. View $S_8$ as being the group of permutations of $\lbrace \infty,0,\dots,6 \rbrace$ and let $\varphi:PSL(2,7) \to S_8$ be the monomorphism arising as in Proposition 3.1 from the action of $PSL(2,7)$ on $\mathbb{P}^1(F)$. Show that the image of $\varphi$ is the subgroup of $A_8$ generated by $(0 123456)$, $(142)(356)$ and $(\infty 0)(13)(25)(46)$**.

    Proof

    We know $PSL(2,7)$ is simple, so the image of $PSL(2,7)$ under $\varphi$ would be a subgroup of $A_8$ (because determinant $=1$ corresponds to even permutations) that is isomorphic to $PSL(2,7)$.

    (The image of natural projection of) the matrix $\begin{pmatrix} 1&0\\1&1 \end{pmatrix}$ is of course an element in $PSL(2,7)$. On the other hand, consider the (set-wise) stabilizer of $\lbrace 0,\infty \rbrace$:

    By some direct matrix multiplication calculation, if we want to map $0 \mapsto 0$ and $\infty \mapsto \infty$, i.e. $\begin{pmatrix} a&b\\c&d \end{pmatrix}\begin{pmatrix} 1\\0 \end{pmatrix} = \begin{pmatrix} x\\0 \end{pmatrix}$ and $\begin{pmatrix} a&b\\c&d \end{pmatrix}\begin{pmatrix} 0\\1 \end{pmatrix} = \begin{pmatrix} 0\\y \end{pmatrix}$, then $b$ and $c$ are forced to be $0$, and $a,d$ are inverse of each other because the matrix has determinant $1$, i.e. we need a matrix of the form $\begin{pmatrix} x&0\\0&x^{-1} \end{pmatrix}$, those matrices are generated by $\begin{pmatrix} 2&0\\0&4 \end{pmatrix}$; and if we want to map $0 \mapsto \infty$ and $\infty \mapsto 0$ then similarly we need a matrix of the form $\begin{pmatrix} 0&-x^{-1}\\x&0 \end{pmatrix}$, those are generated by $\begin{pmatrix} 0&3\\2&0 \end{pmatrix}$.

    Apparently $\begin{pmatrix} 1&0\\1&1 \end{pmatrix}$ cannot be generated by the other two matrices. Since stabilizer of doubly transitive action is maximal (we proved this statement for stabilizer of single point, but it is really the same argument for the set-wise stabilizer), the group $\langle \begin{pmatrix} 1&0\\1&1 \end{pmatrix}, \begin{pmatrix} 2&0\\0&4 \end{pmatrix}, \begin{pmatrix} 0&3\\2&0 \end{pmatrix} \rangle$ (under the natural projection) must be the whole $PSL(2,7)$. So the isomorphic image of $PSL(2,7)$ inside $A_8$ must be generated by the permutations induced by those three matrices.

    It is then not hard to verify they correspond to $(0123456)$, $(124)(365)$ (it is the same as $(142)(356)$, just replace $\begin{pmatrix} 2&0\\0&4 \end{pmatrix}$ with $\begin{pmatrix} 4&0\\0&2 \end{pmatrix}$)and $(\infty 0)(13)(25)(46)$ as desired.

    ## P80.4

    **Let $U$ be the subgroup of $GL(n,p)$ consisting of the upper uni-triangular matrices, and let $Q$ be the subgroup of $U$ consisting of all matrices whose $(i,j)$ entry is zero whenever $1 < i < j < n$. Determine $Z(Q)$, and show that $Q/Z(Q)$ is abelian**.

    Proof

    By assumption, $Q$ is the group such that a generic element looks like $$\begin{pmatrix} 1&a_{12}&a_{13}&\dots&a_{1~n-1}&a_{1n} \\ 0&1&0&\dots&0&a_{2n} \\ 0&0&1&\dots&0&a_{3 n}\\ \dots&\dots&\dots&\dots&\dots&\dots\\ 0&0&0&\dots&1&a_{n-1~n}\\ 0&0&0&\dots&0&1\end{pmatrix},$$ i.e. matrices with $1$ on the diagonal, arbitrary on the first row and last column (except for the top left and bottom right corner, of course), and $0$ everywhere else.

    $Z(Q)$ is by definition those $Z \in Q$ such that $ZM = MZ$ for $M \in Q$. Let's denote the terms of $Z$ by $z_{ij}$, of $M$ by $m_{ij}$, and just do some matrices multiplication. It is not very hard to see that (for a fixed $Z$): $ZM = MZ$ if and only if $z_{12}m_{2n} + z_{13}m_{3n}+\dots +z_{1~n-1}m_{n-1~n}$ $= m_{12}z_{2n} + m_{13}z_{3n}+\dots +m_{1~n-1}z_{n-1~n}$, for **all** $M \in Q$, so the only choice is to have all those $z_{ij}$'s to be $0$. The term we are not touching is $z_{1n}$, so a generic element of $Z(Q)$ is a matrix with $1$ on the diagonal, arbitrary on the top right corner, and $0$ everywhere else.

    The center is always a normal subgroup, so the quotient is always a group, we just need to show it is abelian.

    Notice if we multiply a matrix by such $Z$, we merely add $z_{1n}$ to the top right corner of the original matrix $$\begin{pmatrix} 1&a_{12}&a_{13}&\dots&a_{1~n-1}&\boxed{a_{1n}} \\ 0&1&0&\dots&0&a_{2n} \\ 0&0&1&\dots&0&a_{3 n}\\ \dots&\dots&\dots&\dots&\dots&\dots\\ 0&0&0&\dots&1&a_{n-1~n}\\ 0&0&0&\dots&0&1\end{pmatrix} \mapsto \begin{pmatrix} 1&a_{12}&a_{13}&\dots&a_{1~n-1}&\boxed{a_{1n}+z_{1n}} \\ 0&1&0&\dots&0&a_{2n} \\ 0&0&1&\dots&0&a_{3 n}\\ \dots&\dots&\dots&\dots&\dots&\dots\\ 0&0&0&\dots&1&a_{n-1~n}\\ 0&0&0&\dots&0&1\end{pmatrix}.$$ It means each coset in the quotient consists precisely all matrices that only differ at the top right corner, and we may choose to use the matrices with $0$ at the top right corner to represent each coset.

    Now if we multiply $A, B \in Q$ in two ways $A B$ and $B A$, it is not hard to see the result differs only possibly at the top right corner, but we chose to force the top right corner to be zero, so the result is always the same in the quotient group, and thus the group is abelian as desired.

    ## P80.6

    **Let $U$ be the subgroup of $GL(3, p)$ consisting of the upper uni-triangular matrices. Show that if $p$ is an odd prime, then $U$ is a non-abelian group of order $p^3$ having no elements of order $p^2$. If $p = 2$, with which group of order $8$ is $U$ isomorphic**?

    Proof

    $U = \lbrace \begin{pmatrix} 1&a&b\\0&1&c\\0&0&1\end{pmatrix} | a,b,c \in \mathbb{Z}_p \rbrace$, so $| U | = p^3$ because each $a,b,c$ can be chose from $p$ different elements. Consider the matrices $A = \begin{pmatrix} 1&1&0 \\ 0&1&0 \\ 0&0&1 \end{pmatrix}$ and $B = \begin{pmatrix} 1&0&0\\0&1&1\\0&0&1 \end{pmatrix}$, then $A, B \in U$ and we can calculate $AB = \begin{pmatrix} 1&1&1\\0&1&1\\0&0&1 \end{pmatrix}$ $\ne \begin{pmatrix} 1&1&0\\0&1&1 \\0&0&1 \end{pmatrix}=BA$, so $U$ is not abelian.

    Moreover, if $p$ is odd, a direct calculation gives $\begin{pmatrix} 1&a&b\\0&1&c\\0&0&1 \end{pmatrix}^p$ $=\begin{pmatrix} 1&pa&pb+\sum\limits_{i=1}^{p-1}i\cdot ac \\ 0&1&pc \\ 0&0&1 \end{pmatrix}$ which equals the identity matrix already for any $a,b,c$, because the coefficient are all divisible by $p$ ($\sum\limits_{i=1}^{p-1}i$ $= 1+2+\dots+p-1$, add first with last, second to second-last, etc, since $p$ is odd, this equals $p+p+\dots+p$ is divisible by $p$). Thus any matrix in $U$ has at most order $p$, thus cannot have order $p^2$.

    If $p = 2$, we may identify $$\begin{pmatrix} 1&0&0 \\ 0&1&0 \\ 0&0&1 \end{pmatrix} = 1,\begin{pmatrix} 1&1&0 \\ 0&1&0 \\ 0&0&1 \end{pmatrix} = a,\begin{pmatrix} 1&0&1 \\ 0&1&0 \\ 0&0&1 \end{pmatrix} = b$$ and verify that $a^4 = b^2 = 1$, $b^{-1}ab = a^{-1}$, and that this group is isomorphic to the dihedral group $D_4$.

    ## P174.9

    **Let $G = GL(2, q)$ where $q$ is any prime power. Then $| G | = q(q-1)^2(q+1)$. Denote by $m_g(X)$ the minimal polynomial of an element $g \in G$. Show that if $m_g(X) = X-a$ for some $a \in \mathbb{F}_q^{\times}$, then $g = \begin{pmatrix} a&0\\0&a \end{pmatrix} \in Z(G)$**.

    Proof

    We will be doing several matrices multiplications and solve several systems. For convenience, say $g = \begin{pmatrix} x&y\\z&w \end{pmatrix}$ in matrix form.

    By assumption we have $g - aI = 0$, i.e. $$\begin{pmatrix} x&y\\z&w \end{pmatrix}-\begin{pmatrix} a&0\\0&a \end{pmatrix} = \begin{pmatrix} 0&0\\0&0 \end{pmatrix}$$ so $x = a$, $y = 0$, $z = 0$, and $w = a$, thus $g$ is of the form $\begin{pmatrix} a&0\\0&a \end{pmatrix}$. Since $g$ of this form can be written as $aI$ with inverse $\frac{1}{a}I$, it must lie in the center. In particular, those $g$'s are in their own conjugacy classes, and there are $q-1$ of them, one for each $a$.

    ## P174.10

    **Show that if $m_g(X) = (X-a)^2$ for some $a \in \mathbb{F}_q^{\times}$, then $g$ is conjugate with $\begin{pmatrix} a&1\\0&a \end{pmatrix}$, and the conjugacy class of $g$ has order $q^2 - 1$**.

    Proof

    Expand $(g-aI)^2 = 0$, we will get a system $$\begin{cases} (x-a)^2+yz &= 0\\ y(w+x-2a) &= 0\\z(w+x-2a) &=0\\ (w-a)^2+yz &= 0\end{cases}.$$ Since $m_g(X)$ is assumed not $X-a$, we cannot have both $y, z = 0$. If they are both not zero, then $x=w = \sqrt{-yz}+a \ne a$ but $x+w = 2a$, which is impossible. So one of them is zero and the other is not, so $g$ is of the form $$g = \begin{pmatrix} a&b\\0&a \end{pmatrix}\text{ or }\begin{pmatrix} a&0\\b&a \end{pmatrix}, b \ne 0.$$ It is not hard to verify they are both conjugate to $\begin{pmatrix} a&1\\0&a \end{pmatrix}$, for example: $$\begin{pmatrix} b&0\\0&1 \end{pmatrix}^{-1}\begin{pmatrix} a&b\\0&a \end{pmatrix}\begin{pmatrix} b&0\\0&1 \end{pmatrix} = \begin{pmatrix} a&1\\0&a \end{pmatrix}.$$ To see the order of the conjugacy class, by direct calculation it is not hard to see the stabilizer of $\begin{pmatrix} a&1\\0&a \end{pmatrix}$ is of the form $\begin{pmatrix} x&y\\0&x \end{pmatrix}$; $x$ can be taken in $\mathbb{F}_q^{\times}$ and $y$ is completely arbitrary, so the order of the stabilizer is $q(q-1)$, thus orbit-stabilizer theorem tells us the order of the conjugacy class is $(q-1)(q+1) = q^2-1$.

    There are $q-1$ of such conjugacy classes, one for each $a$.

    ## P174.11

    **Show that if $m_g(X) = (X-a)(X-b)$ for some distinct $a,b \in \mathbb{F}_q^{\times}$ then $g$ is conjugate with $\begin{pmatrix} a&0\\0&b \end{pmatrix}$ and the conjugacy class of $g$ has order $q^2+q$**.

    Proof

    Similarly we get a system $$\begin{cases}ab+x^2-ax-bx+yz &= 0 \\ y(x+w-a-b) &= 0 \\ z(x+w-a-b) &= 0 \\ ab+w^2-aw-bw+yz &= 0\end{cases}.$$ Suppose $y,z$ are both non-zero, then $x,w = \frac{a+b\pm\sqrt{\dots}}{2}$ by quadratic formula, but a matrix of this form is conjugate to $\begin{pmatrix} \frac{a+b}{2}&1 \\ 0&\frac{a+b}{2} \end{pmatrix}$ and falls in the above category. Otherwise at least one of $y,z$ is zero, forcing $x = a, w =b$ or $w =a, x= b$. A direct calculation shows that matrices of the form $$\begin{pmatrix} a&0\\0&b \end{pmatrix},\begin{pmatrix} b&0\\0&a \end{pmatrix},\begin{pmatrix} a&c\\0&b \end{pmatrix},\begin{pmatrix} a&0\\c&b \end{pmatrix}$$ are all in the same conjugacy class, as desired.

    The order of the conjugacy class is calculated in a similar manner as well. We may calculate $$\begin{pmatrix} x&y\\z&w \end{pmatrix}^{-1}\begin{pmatrix} a&0\\0&b \end{pmatrix}\begin{pmatrix} x&y\\z&w \end{pmatrix} = \begin{pmatrix} \frac{awx-byz}{wx-yz}&\frac{awy-bwy}{wx-yz}\\\frac{-axz+bxz}{wx-yz}&\frac{bwx-ayz}{wx-yz} \end{pmatrix},$$ we can see the stabilizer consists of matrix of the form $\begin{pmatrix} x&0\\0&w \end{pmatrix}$ where $x,w \in \mathbb{F}_q^{\times}$ so has order $(q-1)^2$, and thus the conjugacy class has order $q(q+1) = q^2+q$.

    There are $(q-1)(q-2)/2$ of distinct unordered such $a,b$, so there are $(q-1)(q-2)$ such conjugacy classes.

    ## P174.12

    **Show that if $r,s \in \mathbb{F}_q$ are such that $X^2-rX-s$ is irreducible, then the conjugacy class of $\begin{pmatrix} 0&1\\s&r \end{pmatrix}$ has order $q^2-q$**.

    Proof

    Similarly we have a system $$\begin{cases}x^2-rx+yz-s &= 0 \\ y(x+w-r) &= 0 \\ z(x+w-r) &= 0 \\ w^2-rw+yz-s &= 0\end{cases}.$$ It is impossible to have at least one of $y,z$ being zero, because that forces $x^2-rx-s =0$, which is an irreducible quadratic polynomial, implies that $x \notin \mathbb{F}_{q}$. So neither of $y,z$ is zero. Now if $yz \ne s$, or equivalently if both $x,w$ are not zero, then this matrix is conjugate to a certain matrix in category $2$; so $yz=s$ and one of $x,w$ is $r$, the other is $0$. It is not hard to verify $$\begin{pmatrix} 0&1\\s&r \end{pmatrix},\begin{pmatrix} r&1\\s&0 \end{pmatrix},\begin{pmatrix} 0&a\\s/a&r \end{pmatrix},\begin{pmatrix} r&a\\s/a&0 \end{pmatrix}$$ are all conjugate, as desired.

    Again we count the stabilizer, by considering $$\begin{aligned}\begin{pmatrix} x&y\\z&w \end{pmatrix}\begin{pmatrix} 0&1\\s&r \end{pmatrix}=\begin{pmatrix} sy&x+ry\\sw&rw+z \end{pmatrix}\\=\begin{pmatrix} z&w\\sx+rz&rw+sy \end{pmatrix}=\begin{pmatrix} 0&1\\s&r \end{pmatrix}\begin{pmatrix} x&y\\z&w \end{pmatrix}\end{aligned},$$ we either have $x=w, y=z = 0$ (there are $q-1$ of such) or $y =z/s = (w-x)/r$, where if $y \in \mathbb{F}_q^{\times}$ and $w \in \mathbb{F}_q$ are chosen, $x,z$ are fixed. In total the order of stabilizer is $(q-1)(q+1)$ thus order of conjugacy class is $q^2-q$.

    The number of such conjugacy class is the same as the number of irreducible monic quadratic polynomials in $\mathbb{F}_q$, which equals $q^2$ (total number of monic polynomial) minus $\frac{q(q+1)}{2}$ (number of polynomials of the form $(x-r)(x-s)$ or $(x-r)^2$, i.e. reducible ones), which equals $q(q-1)/2$.

    ## P174.13

    **Verify that what follows is a complete list of the conjugacy classes of $G$: $q-1$ classes of $1$ element each, indexed by elements of $\mathbb{F}_q^{\times}$; $q-1$ classes of $q^2-1$ elements each, indexed by elements of $\mathbb{F}_q^{\times}$; $(q-1)(q-2)/2$ classes of $q^2+q$ elements each, indexed by unordered pairs of distinct elements of $\mathbb{F}_q^{\times}$; and $q(q-1)/2$ classes of $q^2-q$ elements each, indexed by irreducible monic quadratic polynomials with coefficients in $\mathbb{F}_q$**.

    Proof

    This is an immediate result followed by preceding problems, and just to make sure: calculate $$\begin{aligned}(q-1)\cdot 1 + (q-1)\cdot(q^2-1) \\+ (q-1)(q-2)(q^2+q)/2 + q(q-1)&(q^2-q)/2 \\&= q(q-1)^2(q+1)\end{aligned}$$ so indeed we have everything covered.
    """
    )
    return


@app.cell
def _(mo):
    mo.md(r"""# Spring Semester Homework 2""")
    return


@app.cell
def _(mo):
    mo.md(
        r"""
    ## Exercise 1

    **Let $G = \mathbb{Z}_3 = \langle a \rangle$, $V = \mathbb{C}G$ viewed as a $\mathbb{C}G$-module. Check that $a$ acts on $V$ by** $$\alpha = \begin{pmatrix} 0&0&1\\1&0&0\\0&1&0 \end{pmatrix}.$$ **Find three one-dimensional submodules of $V$ and conclude $V$ is semi-simple**.

    Solution

    View $v \in V = \mathbb{C}G$ as vectors $\langle x,y,z \rangle$ then $1\cdot v = \langle x,y,z \rangle$; since $\alpha$ (thus $\alpha^2$ and $\alpha^3 = I$) can be viewed as permutation, $G$ acts on $V$.

    If we take $u_1 = 1 + a + a^2$ then certainly $\mathbb{C}u_1$ is a one-dimensional submodule. There are two others using the other two third roots of unity: if $u_2 = 1+e^{\frac{2}{3}\pi i}a + e^{\frac{4}{3}\pi i}a^2$ then $au_2 = e^{\frac{4}{3}\pi i} + a + e^{\frac{2}{3}\pi i}a^2$ $= e^{\frac{4}{3}\pi i}u_2$, because $e^{\frac{6}{3}\pi i} = 1$; similarly for $u_3 = 1 + e^{-\frac{2}{3}\pi i}a + e^{-\frac{4}{3}\pi i}a^2$. It is easy to see $u_1, u_2, u_3$ are linearly independent; since the dimension matches we have $V = \mathbb{C}u_1 \oplus \mathbb{C}u_2 \oplus \mathbb{C}u_3$, so $V$ is a (direct) sum of simple modules (one-dimensional submodules is always simple), thus is semi-simple.

    ## Exercise 2

    **Let $R = F[X]$ and define three different $R$-module structures on $F^2$ (call them $V_1, V_2, V_3$), with $X$ acting by** $$\alpha_1 = \begin{pmatrix} 1&1\\0&1 \end{pmatrix}, \alpha_2 = \begin{pmatrix} 0&1\\-1&0 \end{pmatrix}, \alpha_3 = \begin{pmatrix} 0&1\\1&0 \end{pmatrix}$$ **respectively. Which of these modules are semi-simple and how do they decompose for**:

    1. **$F = \mathbb{C}$**?
    2. **$F = \mathbb{R}$**?
    3. **$F = \mathbb{F}_5$**?

    Solution

    1. If $F = \mathbb{C}$:
    	1. $e_1$ is an eigenvector for (any polynomial of) $\alpha_1$, so $Fe_1$ is a submodule of $F^2$. Any vector $\begin{pmatrix} a\\b \end{pmatrix}, b \ne 0$ cannot be an eigenvector, in particular there is no other non-trivial submodules, and thus $V_1$ is not semi-simple;
    	2. For $\alpha_2$, solve for the characteristic function we get $\lambda^2+1^2 = 0$ $\implies \lambda = \pm i$, so that $u_1 = \begin{pmatrix} 1\\ i \end{pmatrix}$ and $u_2=\begin{pmatrix} 1\\-i \end{pmatrix}$ are always eigenvectors. They are independent, and we get two (simple) submodules, $V_2$ is semi-simple;
    	3. Similarly, $\alpha_3$ always have $u_1 = \begin{pmatrix} 1\\1 \end{pmatrix}$, $u_2 = \begin{pmatrix} 1\\-1 \end{pmatrix}$ as eigenvectors, so $V_3$ is semi-simple;
    2. If $F = \mathbb{R}$:
    	1. The module given by $\alpha_1$ is still not semi-simple for the same reason;
    	2. For $\alpha_2$ there is no solution for $\lambda^2 + 1^2 = 0$ in $\mathbb{R}$, in fact, $V_2$ in this case is isomorphic to $\mathbb{R}[x]/(x^2+1)$. Since $x^2 + 1$ is irreducible thus the ideal is maximal, we have $V_2$ is simple thus semi-simple;
    	3. The module given by $\alpha_3$ is still semi-simple for the same reason;
    3. If $F = \mathbb{F}_5$:
    	1. The module given by $\alpha_1$ is still not semi-simple;
    	2. For $\alpha_2$, we solve $\lambda^2 + 1^2 = 0$ gives $\lambda = 2, 3$, correspond to $u_1 = \begin{pmatrix} 3\\1 \end{pmatrix}$ and $u_2 = \begin{pmatrix} 2\\1 \end{pmatrix}$ (for example $\begin{pmatrix} 0&1\\-1&0 \end{pmatrix}\begin{pmatrix} 3\\1 \end{pmatrix} = \begin{pmatrix} 1\\-3 \end{pmatrix}$ $=\begin{pmatrix} 1\\2 \end{pmatrix}$ $=2 \begin{pmatrix} 3\\1 \end{pmatrix}$), and that $V_2$ is semi-simple;
    	3. The module given by $\alpha_3$ is still semi-simple.

    ## Exercise 3

    **Let $G = D_8 = \langle a,b: a^4 = b^2 = 1, b^{-1}ab = a^{-1} \rangle$. Find three one-dimensional submodules $\mathbb{C}u_i$ of $\mathbb{C}G$ ($i = 1,2,3$) such that** $$\begin{aligned} au_1 &= u_1, &bu_1 &= -u_1 \\ au_2 &= -u_2,&bu_2 &= u_2 \\ au_3 &= -u_3, &bu_3 &= -u_3 \end{aligned}.$$

    Solution

    Look at the Cayley table for $D_8$, we need two rows of it: $$\begin{array} {|r|r|r|r|r|r|r|r|r|}\hline  & 1 & a & a^2 & a^3 & b & ab & a^2b & a^3b \\ \hline a & a & a^2 & a^3 & 1 & ab & a^2b & a^3b & b \\ \hline b & b & a^3b & a^2b & ab & 1 & a^3 & a^2 & a \\ \hline \end{array}$$ Then for example: $a1 = a$, thus if $au_1 = u_1$ then the coefficient of $1$ in $u_1$ must be the same as the coefficient of $a$ in $u_1$, and so on. We should be able to find:

    1. If we take $u_1 = 1+a+a^2+a^3-b-ab-a^2b-a^3b$, then $au_1 = a+a^2+a^3+1-ab-a^2b-a^3b-b = u_1$, and $bu_1 = b+a^3b+a^2b+ab-1-a^3-a^2-a = -u_1$;
    2. Similarly if $u_2 = 1-a+a^2-a^3+b-ab+a^2b-a^3b$, then $au_2 = a-a^2+a^3-1+ab-a^2b+a^3b-b = -u_2$, and $bu_2 = b-a^3b+a^2b-ab+1-a^3+a^2-a = u_2$;
    3. And if $u_3 = 1-a+a^2-a^3-b+ab-a^2b+a^3b$, then $au_3 = a-a^2+a^3-1-ab+a^2b-a^3b+b = -u_3$, and $bu_3 = b-a^3b+a^2b-ab-1+a^3-a^2+a = -u_3$.

    And then $\mathbb{C}u_i$ are the one-dimensional submodules we want.

    ## Exercise 4 (P145.3)

    **Show that if $S$ is a simple $\mathbb{C}G$-module and $U$ is a one-dimensional $\mathbb{C}G$-module, then $S \otimes U$ is simple**.

    Proof

    Since $U$ is one-dimensional (i.e. $U = \mathbb{C}u$), by definition we know $S \otimes U =$ $span\lbrace s_i \otimes u | i \in I \rbrace$ for some index set $I$. $G$ acts on $S \otimes U$ by $g(s_i \otimes u) = (gs_i) \otimes (gu)$. Suppose $V$ is a submodule of $S \otimes U$, then it must be $span\lbrace s_j \otimes u | j \in J \rbrace$ for some index set $J \subset I$ (because it is a subgroup in the first place). That is to say, since $G$ acts on $V$, we need $g(s_j \otimes u) = (gs_j) \otimes (gu) \in V$ to make $V$ a submodule. So $gs_j \in span\lbrace s_j | j \in J \rbrace$ for any $g$, which by definition means $span\lbrace s_j \rbrace$ is a submodule of $S$.

    The upshot is that $V$ is of the form $S' \otimes U$ where $S'$ is a submodule of $S$. But $S$ is by assumption simple, thus $V$ is either $S \otimes U$ or $0 \otimes U \cong 0$, which means $S \otimes U$ has no non-trivial submodule, so by definition it is simple.

    Another method is to let $\chi_S, \chi_U$ be the corresponding irreducible characters such that $\chi_U(1) = 1$, and check $\chi_S\chi_U$ is an irreducible character.

    ## Exercise 5

    **Let $n \ge 3$ be odd, consider the group $H = H_{8n}$ of order $8n$ given by** $$H_{8n}=\langle a,b:a^{2n} = b^4 = 1,ba = a^{-1}b^{-1},b^{-1}a = a^{-1}b \rangle.$$

    1. **Show that if $\varepsilon$ is any $n$-th root of unity in $\mathbb{C}$, then** $$a \to \begin{pmatrix} \varepsilon&0\\0&-\varepsilon^{-1} \end{pmatrix},  b \to \begin{pmatrix} 0&1\\-1&0 \end{pmatrix}$$ **is a representation of $H$. Check that all these representations are irreducible and non-isomorphic**;
    2. **There are further $n-1$ irreducible representations of $H$, which are associated to the $2n$-th roots of unity $\eta = e^{\pi i s/n}, 1 \le s \le n-1$. In these representations $b \to \begin{pmatrix} 0&1\\1&0 \end{pmatrix}$. Write them down and explain why they are irreducible, distinct and different from the ones in part 1**;
    3. **Now you almost have complete list of simple $\mathbb{C}H$-modules, but not quite. Complete it**.

    Proof

    1. Let's denote $A,B$ as the two matrices and do some matrix multiplication: $A^m = \begin{pmatrix} \varepsilon^m&0\\0&(-1)^m\varepsilon^{-m} \end{pmatrix}$. Since $n$ is odd, we must have $A^{2n} = I$ and no smaller $m$ gives $A^m = I$. Also $B^4 = I$ and $B^2, B^3 \ne I$. So the orders match. Also $BA = \begin{pmatrix} 0&-\varepsilon^{-1}\\-\varepsilon&0 \end{pmatrix} = A^{-1}B^{-1}$, and $B^{-1}A = \begin{pmatrix} 0&\varepsilon^{-1}\\\varepsilon&0 \end{pmatrix} =A^{-1}B$. So the relations also match, thus we have a representation.
    	If $A, B$ are reducible then they are simultaneously diagonalizable, which happens if and only if they commute, and which implies they share an eigenvector. However $A$ has eigenvector $\begin{pmatrix} 1\\0 \end{pmatrix}, \begin{pmatrix} 0\\1 \end{pmatrix}$ while $B$ has $\begin{pmatrix}1\\i  \end{pmatrix},\begin{pmatrix}  -1\\i\end{pmatrix}$. So this is an irreducible representation.
    	Isomorphic representations have the same character. Since $\varepsilon - \varepsilon^{-1}$ $= e^{\pi i 2 m/n} - e^{-\pi i 2 m/n}$ $=2i \sin(\frac{2\pi m}{n})$ and if $n\ge 3$ is odd, those values are always distinct if $2m/n \le 2$ (because they need to be symmetric about $\frac{1}{2}$ or $\frac{3}{2}$, which never happen if $n$ is odd), thus none of those representations are isomorphic;
    2. Those representations map $a$ to $A = \begin{pmatrix} \eta&0\\0&\eta^{-1} \end{pmatrix}$. Since $A^m = \begin{pmatrix} \eta^{m}&0\\0&\eta^{-m} \end{pmatrix}$, $A$ has order $2n$. $B$ has order $2 | 4$, and the relations all match, so these are representations.
    	They are irreducible for the very same reason: these $A$'s have eigenvectors $\begin{pmatrix} 1\\0 \end{pmatrix}, \begin{pmatrix} 0\\1 \end{pmatrix}$ but $B$ has $\begin{pmatrix} 1\\1 \end{pmatrix},\begin{pmatrix} 1\\-1 \end{pmatrix}$. They are distinct again because the character is never the same: $\eta+\eta^{-1}$ $=2\cos(\pi m/n)$ and cosine is strictly monotone on $[0,\pi]$.
    	It also follows that they are not isomorphic to the representations in part 1, as $\eta + \eta^{-1}$ is always real, but $\varepsilon - \varepsilon^{-1}$ is always pure imaginary (they are possibly the same if they are both $0$, but since $n$ is odd, this is impossible);
    3. The above representations, viewed as submodules, are all of dimension $2$. We know $8n$ should be the sum of squares of the dimensions of submodules, so $$8n = n(2^2) + (n-1)(2^2) + \dots,$$ so we are still missing $4$ dimensions. Since there is always trivial module, our only option is to have $4 = 1^2 + 1^2 + 1^2 + 1^2$. In fact those are easy: we just map $a, b$ to $\pm 1, \pm 1$, those all give a one-dimensional submodule. There are $4$ of them, so the dimensions match, and we are done.

    ## Exercise 6
    **Let $G = F_{55} = \langle a,b : a^{11} = b^5 =1, b^{-1}ab = a^3 \rangle$**.

    1. **Show that the derived subgroup of $G$ is $G' = \langle a \rangle$. Check that $G$ has $7$ conjugacy classes of sizes $1,5,5,11,11,11,11$ respectively. What are their representatives**?
    2. **Since $G/G' \cong \mathbb{Z}_5$, $G$ has five linear characters. The remaining two simple $\mathbb{C}G$-modules have dimensions \_\_\_ and \_\_\_ . These considerations together with the orthogonality relations are sufficient to complete the entire character table of $G$. Write it down**.

    Proof

    1. By definition of the commutator subgroup, $G'$ must contain $a^{-1}b^{-1}ab = a^{-1}a^3 = a^2$, since $\gcd{2,11} = 1$, $G'$ must contain $\langle a \rangle$, in particular $| G' | \ge 11$. Since $G'$ is a subgroup of $G$ it has order $\le 55$ and is a divisor of $55$. The only possible such numbers are $11$ or $55$. It cannot be $55$ because that would imply $G$ is abelian itself, which is not, so $G'$ has $11$ elements so it must be $\langle a \rangle$.
    	$1$ forms its own conjugacy class. $G'$ as a normal subgroup is a disjoint union of conjugacy classes: $1$ lies inside of it, there are another two classes in $G'$, $\lbrace a, a^3, a^9, a^{27} = a^5, a^{15} = a^4 \rbrace$, and $\lbrace a^2, a^6, a^{18} = a^7, a^{21} = a^{10}, a^{30} = a^8 \rbrace$.
    	There are $4$ conjugacy classes left, the representatives are $ab, ab^2, ab^3, ab^4$ respectively, and each conjugacy class contains $\lbrace b^i, ab^i, a^2b^1, \dots, a^{10}b^i \rbrace$ for each $i$. For example, $ab$ is conjugate to $b$ by $a^7b$, and $ab$ is conjugate to $a^2b$ by $a^6b$, thus all $a^j b$ is conjugate to $ab$; similar for other powers of $b$.
    	In fact, since all $a^i b^j$ for a fixed $j$ is in the same conjugacy class, we may choose to represent them using $b, b^2, b^3$ and $b^4$, and we can choose $a^{10} = a^{-1}$ to represent the third conjugacy class, making it easier to see the relations in character table;
    2. So we need two numbers such that $55 = 5 \cdot 1^2 + …^2 + …^2$, $1^2 + 7^2$ wouldn't work as that adds a linear character. So the other two modules both have dimension $5$.
    	We start to write the character table. First we can safely get the following: we know what $\chi_{reg}$ is, we know what $\chi_1$ is; character of $1, a$ and $a^{-1}$ would be trivial on the linear character because they are elements of the commutator subgroup. And character of powers of $b$'s has to be powers of $w = e^{2\pi i/5}$'s to match the order. We also know $\chi_6(1) = \chi_7(1) = 5$. Also $\chi_{6,7}(b^i)$ must be $0$, because $1^2+w^2+\dots + (w^4)^2 = 0$ already. Also since $a$ and $a^{-1}$ are in different conjugacy classes, those values are needed to be complex conjugate. So we have: $$\begin{array} {|r|r|r|r|r|r|r|r|}\hline  & 1 & a & a^{-1} & b & b^2 & b^3 & b^4 \\ \hline C_i & 55 & 11 & 11 & 5 & 5&5&5  \\ \hline \chi_1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 \\ \hline \chi_2 & 1 & 1 & 1 & w & w^2 & w^3 & w^4 \\ \hline \chi_3 & 1 & 1 & 1 & w^2 & w^4 & w & w^3 \\ \hline \chi_4 & 1 & 1 & 1 & w^3 & w & w^4 & w^2 \\ \hline \chi_5 & 1 & 1 & 1 & w^4 & w^3 & w^2 & w \\ \hline 5\chi_6 & 5 & c & \overline{c} & 0 & 0 & 0 & 0 \\ \hline 5\chi_7 & 5 & \overline{c} & c & 0 & 0 & 0 & 0 \\ \hline \chi_{reg} & 55 & 0 & 0 & 0 & 0 & 0 & 0 \\ \hline  \end{array}$$ Write $c = x+ y i$, then $\chi_{reg}(a) = 0$ gives that $5+5x+5yi + 5x - 5y i = 0$ thus $x = -\frac{1}{2}$. Orthogonality relation $\langle \chi_6, \chi_6 \rangle = 1$ gives that $1 = \frac{25}{55} + 2\cdot\frac{(x+yi)(x-yi)}{11}$ so $3 = x^2+y^2$ and $y = \frac{\sqrt{11}}{2}$ , this gives the complete character table $$\begin{array} {|r|r|r|r|r|r|r|r|}\hline  & 1 & a & a^{-1} & b & b^2 & b^3 & b^4 \\ \hline C_i & 55 & 11 & 11 & 5 & 5&5&5  \\ \hline \chi_1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 \\ \hline \chi_2 & 1 & 1 & 1 & w & w^2 & w^3 & w^4 \\ \hline \chi_3 & 1 & 1 & 1 & w^2 & w^4 & w & w^3 \\ \hline \chi_4 & 1 & 1 & 1 & w^3 & w & w^4 & w^2 \\ \hline \chi_5 & 1 & 1 & 1 & w^4 & w^3 & w^2 & w \\ \hline 5\chi_6 & 5 & \frac{-1+\sqrt{-11}}{2} & \frac{-1-\sqrt{-11}}{2} & 0 & 0 & 0 & 0 \\ \hline 5\chi_7 & 5 & \frac{-1-\sqrt{-11}}{2} & \frac{-1+\sqrt{-11}}{2} & 0 & 0 & 0 & 0 \\ \hline \chi_{reg} & 55 & 0 & 0 & 0 & 0 & 0 & 0 \\ \hline  \end{array}$$

    ## Exercise 7

    **Let $\chi$ be the character of the $\mathbb{C}G$-module $V$, and denote by $\chi_S$, $\chi_{\Lambda}$ the characters of the $\mathbb{C}G$-modules $S^2V$ and $\Lambda^2V$ respectively**.

    1. **Show that for $g \in G$,** $$\begin{aligned}2\chi_S(g) &= \chi(g)^2 + \chi(g^2),\\ 2\chi_{\Lambda}(g) &= \chi(g)^2 - \chi(g^2);\end{aligned}$$
    2. **Let now $| G | = 24$ and $g_i (1 \le i \le 7)$ be the representatives of seven conjugacy classes $\mathcal{K}_i$ in $G$ of sizes $1,1,6,4,4,4,4$ respectively. Moreover $g_i^2$ is conjugate to $g_1, g_1, g_2, g_5, g_4, g_4, g_5$ respectively. Let $\chi$ be the character of $G$, where $\chi(g_i)$ is $2, -2, 0, -w^2, -w,w,w^2$ respectively ($w = e^{2\pi i/3}$). Is $\chi$ irreducible? Find $\chi_S$ and $\chi_{\Lambda}$ and check whether they are irreducible. Complete the character table of $G$**.

    Proof
    1. Take $g \in G$ and choose basis $\lbrace e_1,\dots, e_k \rbrace$ of $V$ such that $g$ acts diagonally, i.e. $ge_i = \lambda_ie_i$. Now we know $\lbrace e_i \otimes e_j + e_j \otimes e_i | 1 \le i \le j \le k\rbrace$ form a basis for $S^2V$, and we have $$g(e_i \otimes e_j + e_j \otimes e_i) = \lambda_ie_i \otimes \lambda_je_j + \lambda_je_j \otimes \lambda_ie_i = \lambda_i\lambda_j(e_i \otimes e_j + e_j \otimes e_i),$$ so $\chi_S(g)$ is just the sum of $\lambda_i\lambda_j$ over $1 \le i \le j \le k$, i.e. $$\chi_S(g) = \sum_{1 \le i \le j \le k}\lambda_i \lambda_j.$$ Similarly, we have $$\chi_{\Lambda}(g) = \sum_{1 \le i < j \le k}\lambda_i\lambda_j,$$ notice there is a slight difference in the summand indices.
    	Now we verify the above equalities:
    	By the construction we have $\chi(g) = \sum\limits_i \lambda_i$, thus $\chi(g)^2$ $= (\sum \lambda_i)^2$ $= \sum\limits_i \lambda_i^2 + 2\sum\limits_{1 \le i < j \le k}\lambda_i\lambda_j$. Also since $ge_i = \lambda_ie_i$, we have $g^2e_i = \lambda_i^2e_i$, so $\chi(g^2) = \sum\limits_i \lambda_i^2$. It is straight-forward now to see $$2\chi_{\Lambda}(g) = \chi(g)^2 - \chi(g^2).$$ The other equality $$2\chi_S(g) = \chi(g)^2 + \chi(g^2)$$ also follows, by merely noticing $\sum\limits_i\lambda_i^2 = \sum_{1\le i = j \le k}\lambda_i\lambda_j$;
    2. The conjugacy classes have sizes $1,1,6,4,4,4,4$, so the centralizers have sizes $24, 24, 4, 6, 6, 6, 6$. First we check the orthogonality relation: $$\langle \chi, \chi \rangle = \frac{4}{24} + \frac{4}{24} + \frac{1}{6} +\frac{1}{6} + \frac{1}{6}+ \frac{1}{6} = 1$$ ($w\overline{w}$ is $1$), so $\chi$ is irreducible. From the conjugation information we have, we get $$\chi(g^2) = \chi(g_1), \chi(g_1), \chi(g_2), \chi(g_5), \chi(g_4), \chi(g_4),\chi(g_5) = 2,2,-2,-w,-w^2,-w^2,-w.$$ Also $$\chi(g)^2 = 4, 4, 0, w^4, w^2, w^2, w^4.$$ With the above relation we have, we get $$\chi_S(g) = 3,3,-1,0,0,0,0$$ (because $w^4 - w^1 = 0$), and $$\chi_{\Lambda}(g) = 1,1,1,w,w^2,w^2,w.$$ We can again use the orthogonality relation to see they are both irreducible. So up to now we have $$\begin{array} {|r|r|r|r|r|r|r|r|}\hline  & g_1 & g_2 & g_3 & g_4 & g_5 & g_6 & g_7 \\ \hline C_i & 24 & 24 & 4 & 6 & 6 & 6 & 6 \\ \hline \chi_1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 \\ \hline \chi & 2 & -2 & 0 & -w^2 & -w & w & w^2 \\ \hline \chi_{\Lambda} & 1 & 1 & 1 & w & w^2 & w^2 & w \\ \hline \chi_S & 3 & 3 & -1 & 0 & 0 & 0 & 0 \\ \hline \chi_2 &  &  &  &  &  &  &  \\ \hline \chi_3 &  &  &  &  &  &  &  \\ \hline \chi_4 &  &  &  &  &  &  &  \\ \hline \chi_{reg} & 24 & 0 & 0 & 0 & 0 & 0 & 0 \\ \hline  \end{array}$$ From the $\chi_{reg}$ condition we need $3$ positive integers with sum of squares $= 9$, and there is only one way to do so, namely $2^2 + 2^2 + 1^2 = 9$. So there are $3$ linear character and we can get the third one is $$\chi_2(g) = 1,1,1,w^2,w,w,w^2$$ by taking the 'inverse' of $\chi_{\Lambda}$. Now we can use $$(\chi_{\Lambda}\cdot\chi) (g) = 2,-2,0,-1,-1,1,1,$$ which must also be an irreducible character by Exercise 4. Similarly use $\chi_2\cdot\chi$ we get the last irreducible character, and we complete the table: $$\begin{array} {|r|r|r|r|r|r|r|r|}\hline  & g_1 & g_2 & g_3 & g_4 & g_5 & g_6 & g_7 \\ \hline C_i & 24 & 24 & 4 & 6 & 6 & 6 & 6 \\ \hline \chi_1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 \\ \hline \chi & 2 & -2 & 0 & -w^2 & -w & w & w^2 \\ \hline \chi_{\Lambda} & 1 & 1 & 1 & w & w^2 & w^2 & w \\ \hline \chi_S & 3 & 3 & -1 & 0 & 0 & 0 & 0 \\ \hline \chi_2 & 1 & 1 & 1 & w^2 & w & w & w^2 \\ \hline \chi_3 & 2 & -2 & 0 & -1 & -1 & 1 & 1 \\ \hline \chi_4 & 2 & -2 & 0 & -w & -w^2 & w^2 & w \\ \hline \chi_{reg} & 24 & 0 & 0 & 0 & 0 & 0 & 0 \\ \hline  \end{array}$$

    ## Exercise 8

    **Let $\rho$ be a representation of $G$ over $\mathbb{C}$ and $\delta(g) = \det(\rho(g))$. Then $\delta$ is a linear character of $G$ and $G/\ker{\delta}$ is abelian (why?)**.

    1. **Assume that $\delta(g) = -1$ for some $g \in G$. Show that $G$ has a normal subgroup of index $2$**;
    2. **Let now $\chi$ be a character of $G$, and $h \in G$ be an element of order $2$. Show that either $\chi(h) \equiv \chi(1) \pmod{4}$ or $G$ has a normal subgroup of index $2$**.

    Proof

    0. $\delta$ is a character because if $hgh^{-1} = f$ then $\delta(f) = \det(\rho(hgh^{-1}))$ $=\det(\rho(g))$ $= \delta(g)$, so it is invariant up to conjugacy classes. It is linear because $\delta(1) = \det(\rho(1)) = 1$.
    	$G/\ker{\delta}$ is abelian because $\ker{\delta}$ contains all the commutators: let $x,y$ be arbitrary element of $G$, then $\delta(x^{-1}y^{-1}xy) = \det(\rho(x^{-1}y^{-1}xy))$ $=\det(I) = 1$ because $\rho$ is a homomorphism;
    1. Notice $\delta$ is a homomorphism (because $\rho$ is, and product of determinant is determinant of product). If $\delta(g) = -1$ then it is an element of order $2$ in $\text{im}(\delta)$ where $\text{im}(\delta) \cong G/\ker{\delta}$, so $2$ divides $| \text{im}(\delta) |$. Moreover, since $\delta$ is a linear character, $\text{im}(\delta)$ is cyclic.
    	Now cyclic group has subgroup of any order that divides the order of the cyclic group, and those subgroups are all normal, in particular we have a normal subgroup of $\text{im}(\delta)$ of index $2$, and by Correspondence Theorem, we get a normal subgroup of index $2$ of $G$;
    2. Suppose $G$ does not have a subgroup of index $2$ (such subgroup is of course normal), we want to show that we must have $\chi(h) \equiv \chi(1) \pmod{4}$.
    	By part 1, we must not have $\delta(g) = -1$ for any $g$, but $1 = \delta(h^2) = \delta(h)^2$ so $\delta(h)$ must be $1$.
    	Also $\rho(h)$ either have order $1$ or $2$, so as a matrix we must have that $\rho(h)$, up to conjugacy, is a diagonal matrix with $\pm 1$ on the diagonal. But we know its determinant is $1$, which is the product of those $\pm 1$'s, so we must have even number $2k$ of $-1$'s, and the rest $\chi(1) - 2k$ terms on the diagonal be $1$, then a direct calculation gives us $$\chi(h) = 2k(-1) + (\chi(1)-2k)(1) = \chi(1) - 4k \equiv \chi(1) \pmod{4}$$ as desired.

    ## Exercise 9

    **We say that $g \in G$ is real if $\chi(g) \in \mathbb{R}$ for all irreducible characters $\chi$ of $G$ (or equivalently, $\chi(g) = \chi(g^{-1})$). Prove that if $| G |$ is odd, then no non-identity element of $G$ is real**.

    Proof

    Suppose $1 \ne g \in G$ is real, then $g$ and $g^{-1}$ are conjugate. Suppose $g = g^{-1}$, then $g^2 = 1$; since $g \ne 1$ we have $o(g) = 2$ implies $| G |$ is even, so $g \ne g^{-1}$. Also we know by Orbit-Stabilizer Theorem that order of conjugacy class must divides order of $G$, so in our case all conjugacy classes have odd order. In particular, the conjugacy class of $g$ cannot be just $g$ and $g^{-1}$, say $h$ is also in the conjugacy class.

    By definition it means there is some $f \in G$ such that $fgf^{-1} = h$, but then take inverse both sides we have $fg^{-1}f^{-1} = h^{-1}$, so $h^{-1}$ is also inside the conjugacy class. $1$ has its own conjugacy class, so $h \ne 1$, with the same argument as above we see $h \ne h^{-1}$. This means element in conjugacy class of $g$ always come with pair, so the conjugacy class of $g$ must have even order, but as discussed above, that is impossible.
    """
    )
    return


@app.cell
def _(mo):
    mo.md(r"""# Spring Semester Homework 3""")
    return


@app.cell
def _(mo):
    mo.md(
        r"""
    ## Exercise 1 (P164.10)

    **Determine the character table of $S_5$**.

    Solution

    The conjugacy classes of $S_n$ is determined by cycle types, so we have $()$, $(12)$, $(123)$, $(1234)$, $(12345)$, $(12)(34)$, and $(123)(45)$, in total seven classes, and it is not hard to calculate the size of stabilizers: $C_i = 120, 12, 6, 4, 5, 8, 6$. Since any permutation has the same cycle type as its inverse, we know the whole table is real.

    There are two representations $S_n \to \mathbb{C}^{*}$ for all $S_n$ ($n \ge 2$), the trivial representation sending everything to $1$, or the representation sending odd permutation to $-1$ and even permutation to $1$. We have $$\begin{aligned} \chi_1 &= 1,1,1,1,1,1,1; \\ \chi_2 &= 1,-1,1,-1,1,1,-1.\end{aligned}$$ We also have a natural permutation representation on $\lbrace 1,2,3,4,5 \rbrace$, gives a character $$\chi_{\pi} = 5,3,2,1,0,1,0.$$ This is not an irreducible character, because $\frac{25}{120}+ \frac{9}{12} + \frac{4}{6} + \frac{1}{4} +\frac{1}{8} = 2 \ne 1$. But $\chi_{\pi} - \chi_1$ gives $4,2,1,0,-1,0,-1$ and it is an irreducible character. Use this times $\chi_2$ gives another irreducible character, because product with $\chi_2$ gives a new character with same inner product with itself as all values of $\chi_2$ are $\pm 1$: $$\begin{aligned} \chi_3 &= 4,2,1,0,-1,0,-1; \\ \chi_4 &= 4,-2,1,0,-1,0,1.\end{aligned}$$ Now we need another three characters. To match the dimension we have $a^2 + b^2 + c^2 = 86$, the solutions could be $\lbrace 5,5,6 \rbrace, \lbrace 1,2,9 \rbrace$ or $\lbrace 1,6,7 \rbrace$. Since the dimensions must divide $| S^5 | = 120$, the only option is to have $5,5,6$. Call them $\chi_5, \chi_6, \chi_7$.

    As mentioned above, the product of an irreducible character with $\chi_2$ must give another irreducible character (with the same dimension). Since there is only one character with dimension $6$, $\chi_7\chi_2$ must be $\chi_7$ itself, in particular $\chi_7(g) = 0$ if $\chi_2(g) = -1$. Similarly, $\chi_5\chi_2$ is either $\chi_5$ or $\chi_6$, and $\chi_6\chi_2$ is either $\chi_6$ or $\chi_5$. However, we must have $\chi_5\chi_2 = \chi_6$ and $\chi_6\chi_2 = \chi_5$, otherwise it forces $\chi_5(g) = \chi_6(g) = 0$ whenever $\chi_2(g) = -1$, but this violate the second orthogonality relation, for example consider $g = (12)$, then $\sum\limits_t\chi_t^2(g)$ $= 1+1+4+4$ $= 10 \ne 12$. So up to now we have $$\begin{array} {|r|r|r|r|r|r|r|r|}\hline  & () & (12) & (123) & (1234) & (12345) & (12)(34) & (123)(45) \\ \hline C_i & 120 & 12 & 6 & 4 & 5 & 8 & 6  \\ \hline \chi_1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 \\ \hline \chi_2 & 1 & -1 & 1 & -1 & 1 & 1 & -1 \\ \hline \chi_3 & 4 & 2 & 1 & 0 & -1 & 0 & -1 \\ \hline \chi_4 & 4 & -2 & 1 & 0 & -1 & 0 & 1 \\ \hline \chi_5 & 5 & a & b & c & d & e & f \\ \hline \chi_6 & 5 & -a & b & -c & d & e & -f \\ \hline \chi_7 & 6 & 0 & b' & 0 & d' & e' & 0 \\ \hline \chi_{reg} & 120 & 0 & 0 & 0 & 0 & 0 & 0 \\ \hline \end{array}$$ In fact, by above we need $a^2 + a^2 = 2$, so the only option is to have $a = \pm 1$. WLOG say $a = 1$. Then second orthogonality relation on column $(1234)$ with itself gives that $c = \pm 1$, and second orthogonality relation on column $(12)$ with $(1234)$ gives that $c = -1$. Similarly, $f$ must be $1$. Second orthogonality relation of $(12345)$ with itself shows that $d^2+d^2+(d')^2 = 1$, so $d= 0$ and $d' = \pm 1$. Similarly, $b = \pm 1$ and $b' = 0$, and that $e = \pm 1$ and $e' = \pm 2$.

    (**A Redo**! The above argument does not work since it is not clear why $d, d'$ must be integers. However there is a very easy way to do the calculation: remember we have a character when we introducing tensor products $2\chi_{\Lambda}(g) = \chi(g)^2 - \chi(g^2)$, if we use $\chi_3$ as our $\chi$ here, it won't be too hard to get $\chi_{\Lambda}$ is $\chi_7$ of what we had. To calculate $\chi(g^2)$, for example, if $g = (123)$ then $g^2 = (123)(123) = (132)$ is conjugate to $(123)$ so $\chi(g^2) = 1$, etc. After this, the rest can be then worked out with the way I treated to $a, c$ and $f$.)

    We have: $$\begin{array} {|r|r|r|r|r|r|r|r|}\hline  & () & (12) & (123) & (1234) & (12345) & (12)(34) & (123)(45) \\ \hline C_i & 120 & 12 & 6 & 4 & 5 & 8 & 6  \\ \hline \chi_1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 \\ \hline \chi_2 & 1 & -1 & 1 & -1 & 1 & 1 & -1 \\ \hline \chi_3 & 4 & 2 & 1 & 0 & -1 & 0 & -1 \\ \hline \chi_4 & 4 & -2 & 1 & 0 & -1 & 0 & 1 \\ \hline \chi_5 & 5 & 1 & \pm 1 & -1 & 0 & \pm 1 & 1 \\ \hline \chi_6 & 5 & -1 & \pm 1 & 1 & 0 & \pm 1 & -1 \\ \hline \chi_7 & 6 & 0 & 0 & 0 & \pm 1 & \pm 2 & 0 \\ \hline \chi_{reg} & 120 & 0 & 0 & 0 & 0 & 0 & 0 \\ \hline  \end{array}$$ Now the first orthogonality relation with $\chi_5$ and $\chi_1$ says $\frac{5}{120} + \frac{1}{12} + \frac{\pm 1}{6} - \frac{1}{4} + \frac{\pm 1}{8} + \frac{1}{6} = 0$, so we must have $- \frac{1}{6}$ and $+\frac{1}{8}$. Similarly the first orthogonality relation with $\chi_7$ and $\chi_1$ gives the last information we need, and we have: $$\begin{array} {|r|r|r|r|r|r|r|r|r|}\hline  & () & (12) & (123) & (1234) & (12345) & (12)(34) & (123)(45) \\ \hline C_i & 120 & 12 & 6 & 4 & 5 & 8 & 6  \\ \hline \chi_1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 \\ \hline \chi_2 & 1 & -1 & 1 & -1 & 1 & 1 & -1 \\ \hline \chi_3 & 4 & 2 & 1 & 0 & -1 & 0 & -1 \\ \hline \chi_4 & 4 & -2 & 1 & 0 & -1 & 0 & 1 \\ \hline \chi_5 & 5 & 1 & -1 & -1 & 0 & 1 & 1 \\ \hline \chi_6 & 5 & -1 & -1 & 1 & 0 & 1 & -1 \\ \hline \chi_7 & 6 & 0 & 0 & 0 & 1 & - 2 & 0 \\ \hline \chi_{reg} & 120 & 0 & 0 & 0 & 0 & 0 & 0 \\ \hline  \end{array}$$

    ## Exercise 2

    **Look up the character table of $S_6$, now recover the character table of $A_6$ from it**.

    Solution

    Here is the character table for $S_6$: $$\begin{array} {|r|r|r|r|r|r|r|r|r|r|r|r|}\hline \text{cycle type} & 0 & 2 & 222 & 3 & 33 & 22 & 4 & 24 & 23 & 6 & 5 \\ \hline C_i & 720 & 48 & 48 & 18 & 18 & 16 & 8 & 8 & 6 & 6 & 5 \\ \hline \chi_1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 \\ \hline \chi_2 & 1 & -1 & -1 & 1 & 1 & 1 & -1 & 1 & -1 & -1 & 1 \\ \hline \chi_3 & 5 & 3 & -1 & 2 & -1 & 1 & 1 & -1 & 0 & -1 & 0 \\ \hline \chi_4 & 5 & -3 & 1 & 2 & -1 & 1 & -1 & -1 & 0 & 1 & 0 \\ \hline \chi_5 & 5 & -1 & 3 & -1 & 2 & 1 & 1 & -1 & -1 & 0 & 0 \\ \hline \chi_6 & 5 & 1 & -3 & -1 & 2 & 1 & -1 & -1 & 1 & 0 & 0 \\ \hline \chi_7 & 9 & 3 & 3 & 0 & 0 & 1 & -1 & 1 & 0 & 0 & -1 \\ \hline \chi_8 & 9 & -3 & -3 & 0 & 0 & 1 & 1 & 1 & 0 & 0 & -1 \\ \hline \chi_9 & 10 & 2 & -2 & 1 & 1 & -2 & 0 & 0 & -1 & 1 & 0 \\ \hline \chi_{10} & 10 & -2 & 2 & 1 & 1 & -2 & 0 & 0 & 1 & -1 & 0 \\ \hline \chi_{11} & 16 & 0 & 0 & -2 & -2 & 0 & 0 & 0 & 0 & 0 & 1 \\ \hline  \end{array}$$ The alternating subgroup has $7$ conjugacy classes, which are of cycle type $0$, $22$, $3$, $33$, $24$, and two half of $5$ (for example, $(12345)$ and $(13524)$ are not conjugate inside $A_6$). Much of the information we need are just inherited from $S_6$: $$\begin{array} {|r|r|r|r|r|r|r|r|}\hline \text{cycle type} & 0 & 3 & 33 & 22 & 24 & 5a & 5b \\\hline C_i & 360 & 9 & 9 & 8 & 4 & 5 & 5  \\ \hline \chi_1 & 1 & 1 & 1 & 1 & 1 & 1 & 1\\ \hline \chi_3 & 5 & 2 & -1 & 1 & -1 & 0 & 0\\ \hline \chi_5 & 5 & -1 & 2 & 1 & -1 & 0 & 0\\ \hline \chi_7 & 9 & 0 & 0 & 1 & 1 & -1 & -1\\ \hline \chi_{9} & 10 & 1 & 1 & -2 & 0 & 0 & 0\\ \hline \chi_{11a} & 8 & a & b & c & d & e & f \\ \hline \chi_{11b} & 8 & a' & b' & c' & d' & e' & f' \\ \hline  \end{array}$$ We get two $8$-dimension modules because that is the only integers matches $a^2 + b^2 = 128$. Also remember this table should be all real. We can get $c, c', d, d' = 0$ because the second orthogonality relation ($1+1+1+1+4 = 8$ and $1+1+1+1 = 4$ already). We use the orthogonal relations to solve the rest.

    1. For $a$ and $a'$, we have $a^2 + {a'}^2 + 1 + 1 + 4 + 1 = 9$, so $a^2 + {a'}^2 = 2$, and that $1+10-5+10+8a+8a' = 0$ so $a+a' = -2$, so there is only one solution that $a = a' = -1$;
    2. For $b$ and $b'$, we get $b^2 + {b'}^2 = 2$ and $b + b' = -2$ as well, so $b = b' = -1$;
    3. For $e$ and $e'$, we get $e^2 + {e'}^2 = 3$ and $e + e' = 1$, and we get the same equation for $f$ and $f'$, since no rows are the same, we get $e, e' = \frac{1 \pm \sqrt{5}}{2}$ and $f, f' = \frac{1 \mp \sqrt{5}}{2}$ and we have complete the table: $$\begin{array} {|r|r|r|r|r|r|r|r|}\hline \text{cycle type} & 0 & 3 & 33 & 22 & 24 & 5a & 5b \\\hline C_i & 360 & 9 & 9 & 8 & 4 & 5 & 5  \\ \hline \chi_1 & 1 & 1 & 1 & 1 & 1 & 1 & 1\\ \hline \chi_3 & 5 & 2 & -1 & 1 & -1 & 0 & 0\\ \hline \chi_5 & 5 & -1 & 2 & 1 & -1 & 0 & 0\\ \hline \chi_7 & 9 & 0 & 0 & 1 & 1 & -1 & -1\\ \hline \chi_{9} & 10 & 1 & 1 & -2 & 0 & 0 & 0\\ \hline \chi_{11a} & 8 & -1 & -1 & 0 & 0 & \frac{1+\sqrt{5}}{2} & \frac{1-\sqrt{5}}{2} \\ \hline \chi_{11b} & 8 & -1 & -1 & 0 & 0 & \frac{1-\sqrt{5}}{2} & \frac{1+\sqrt{5}}{2} \\ \hline \end{array}$$

    ## Exercise 3 (P164.8)

    **Show that if $G$ acts doubly transitively on $X$, then the character of $\mathbb{C}X$ is the sum of the principal character and exactly one other irreducible character**.

    Proof

    Let's restate things to get a bit clearer: suppose $G$ acts doubly transitively on $X$ (corresponds to a permutation module), let $\chi$ be the corresponding character. The action of $G$ on $X$ induces the action $G$ on $X \times X$ by $g(x,y) = (gx, gy)$. Let us denote the character corresponds to this action by $\chi_d$.

    First notice that $\chi_d = \chi^2$, this can be seen by counting the fixed point of the action because we have permutation modules: if $g$ acts on $X$ with $n$ fixed points $x_1,\dots,x_n$, then $g$ acts on $X \times X$ has exactly $n \times n$ fixed points $(x_1, x_1),(x_1,x_2),\dots,(x_1,x_n),\dots,(x_n,x_n)$.

    By the discussion in the book, we know that $\langle \chi_d, \chi_1 \rangle$ equals the number of orbits of $X \times X$ under the action of $G$, and by definition of double-transitivity, there are exactly $2$ orbits, namely the diagonal and everything else, so $\langle \chi_d, \chi_1 \rangle = 2$. Since $\chi_d = \chi^2$, we get $\langle \chi_d, \chi_1 \rangle = \langle \chi,\chi \rangle$ (because those are all integers) $= 2$. In particular we must have $\langle \chi, \chi_1 \rangle = 1$, thus we must have $\langle \chi,\chi' \rangle = 1$ for another irreducible character $\chi'$, and $\langle \chi,\chi'' \rangle = 0$ for any other irreducible character.

    It follows that the module corresponds to $\chi$ is a direct sum of trivial module and a simple module, and $\chi = \chi_1 + \chi'$, a sum of principal character and another irreducible character.

    ## Exercise 4

    **Let $G$ be a group of odd order $n$, $\chi_1$ be the trivial character of $G$, and $\eta$ be an irreducible real character of $G$, i.e. $\eta = \overline{\eta}$**.

    1. **Check that** $$\langle \eta,\chi_1 \rangle = \frac{1}{n}(\eta(1) + 2\alpha)$$ **where $\alpha$ is an algebraic integer**;
    2. **Deduce that $\eta = \chi_1$**.

    Solution

    1. If $\eta = \chi_1$ then the statement is obvious: $\eta(1) = 1$, $n$ is odd, thus if we take $\alpha = (n-1)/2$ then it is an integer thus an algebraic integer, and we have $$\langle \eta,\chi_1 \rangle = 1 = \frac{1}{n}(1 + 2\frac{n-1}{2}).$$ Suppose now $\eta \ne \chi_1$. From orthogonality relation we know that $\langle \eta,\chi_1 \rangle = 0$. Expand LHS we have that $$0 = \frac{1}{n}\sum_{g\in G}\eta(g)\overline{\chi_1(g)} = \frac{1}{n}\sum_{g\in G}\eta(g).$$ In particular $$\sum_{g \in G}\eta(g) = \eta(1) + \sum_{g \ne 1}\eta(g) = 0.$$ Now from before we know if $| G |$ is odd then $g \ne g^{-1}$ for all $g \ne 1$ (otherwise this element has order $2$, contradict that $| G |$ is odd), also we know that $\eta(g^{-1})$ $= \overline{\eta(g)}$ $= \eta(g)$ by assumption, so we have $$\begin{align*}0 &= \eta(1) + \sum_{\lbrace g, g^{-1} \rbrace}\eta(g) + \eta(g^{-1}) \\ 0&=\eta(1) + 2 \sum_{\lbrace g, g^{-1} \rbrace}\eta(g) \tag{1} \\ -\frac{\eta(1)}{2} &= \sum_{\lbrace g, g^{-1} \rbrace}\eta(g). \end{align*}$$ The LHS is a fraction, because we know dimension of module must divide order of $G$ so $\eta(1)$ is odd. But a fraction is not an algebraic integer, yet the RHS is a sum of algebraic integers thus an algebraic integer, so we have a contradiction. So $\eta$ must be $\chi_1$ and the statement is true as discussed.
        If we just want to verify the statement, then $(1)$ gives the equation;
    2. Done above.

    ## Exercise 5

    **Let $R \subseteq S \subseteq T$ be domains, suppose all elements of $S$ are $R$-integral and $t \in T$ is $S$-integral. Show that $t$ is $R$-integral**.

    Proof

    Suppose $t \in T$ is an $S$-integer. By definition, $t^n + s_1 t^{n-1} + \dots + s_n = 0$ where $s_i \in S$. In particular, $t$ is integer over $R[s_1, \dots, s_n]$, which means $R[s_1,\dots, s_n, t]$ is a finitely generated $R[s_1,\dots,s_n]$-module. On the other hand, $R[s_1, \dots, s_n]$ is a finitely generated $R$-module because $s_1,\dots,s_n$ are by assumption $R$-integers. Thus $R[s_1,\dots, s_n, t]$ is a finitely generated $R$-module, and thus $t$ is an $R$-integer.

    ## Exercise 6

    **Let $a \in \mathbb{R}$ be a root of $x^3 + 6x + 34 \in \mathbb{Z}[x]$ and $R = \mathbb{Z}[a]$. Show that $R$ is not integrally closed (look at $\frac{1+a}{3}$)**.

    Solution

    Notice if $a^3 + 6a + 34 = 0$, then $$27(\frac{a+1}{3})^3 - 27 (\frac{a+1}{3})^2 + 27(\frac{a+1}{3}) + 27 = a^3+6a+34 = 0,$$ so $\frac{1+a}{3}$ is a $\mathbb{Z}[a]$-integer. But it is not contained in $\mathbb{Z}[a]$:

    Suppose it is, then $\frac{1+a}{3} = b_0 + b_1 a + \dots + b_na^n$ for some $n$ and $b_i \in \mathbb{Z}$, then $(3b_0 - 1) + (3b_1 - 1)a + \dots + 3b_na^n = 0$. Since $a^3+6a+34$ is irreducible, it must be a factor of the above polynomial, but the coefficients do not match modulo $3$: say $$(a^3+6a+34)(c_ma^m + \dots +c_1a^1 + c_0) = (3b_0 - 1) + (3b_1 - 1)a + \dots + 3b_na^n,$$ then $c_m \equiv 0 \pmod{3}$ as the leading coefficient RHS is $3b_n$, and similar for all $c_i$'s, in particular $c_0 \equiv 0 \pmod{3}$, but then the constant term on LHS $\equiv 0 \pmod{3}$, but $\equiv 2 \pmod{3}$ on RHS.

    ## Exercise 7

    **Let $I = (y^2 - x^3)$ be an ideal in the polynomial ring $R = \mathbb{C}[x, y]$ and $S = R/I$**.

    1. **Is $S$ a domain? What does the answer tell us about the ideal $I$**? *Hint: Consider the map $f(x,y) \to f(t^2, t^3) \in \mathbb{C}[t]$ and determine its kernel*.
    2. **Show that $S$ is not integrally closed (and thus not a UFD)**.

    Solution

    1. Consider the map $\varphi: \mathbb{C}[x,y] \to \mathbb{C}[t]$ by $f(x,y) \mapsto f(t^2, t^3)$. Any $f(x,y)$ can be viewed as a polynomial in $y$, also $y^2 - x^3$ can be viewed as a polynomial in $y$, so we can perform an Euclidean division, say $$f(x,y) = (y^2 - x^3)g(x,y) + r(x,y),$$ where the degree of $y$ in $r(x,y)$ is at most $1$, so we can write $$f(x,y) = (y^2-x^3)g(x,y) + r_1(x) + r_2(x)y.$$ The image of this polynomial under $\varphi$ is $$f(t^2,t^3) = (t^6 - t^6)g(t^2, t^3) + r_1(t^2) + r_2(t^2)t^3 = r_1(t^2) + r_2(t^2)t^3.$$ Notice now $r_1(t^2)$ only contains even degree monomials, yet $r_2(t^2)t^3$ only contains odd degree monomials, so they don't 'interact' (in particular, cancel terms when being added, this argument works as long as the powers of $x, y$ are coprime) with each other, so their summation is $0$ if and only if all coefficients of $r_1$ and $r_2$ are $0$. This means the kernel of $\varphi$ consists exactly of those $f$ such that $f(x,y) = (y^2-x^3)g(x,y)$, in other words, $$\ker{\varphi} = (y^2-x^3),$$ and isomorphism theorem tells us $S = \mathbb{C}[x,y]/\ker{\varphi} \cong im{\varphi} \subset \mathbb{C}[t]$. Since $\mathbb{C}$ is a field, it is a domain, thus $\mathbb{C}[t]$ is a domain (Gauss), thus $im{\varphi}$ is an ideal of $\mathbb{C}[t]$ is a domain, thus $S$ is a domain. Also we know that $R/I$ is a domain if and only if $I$ is prime, so $I$ is a prime ideal.
    2. Consider $s = \frac{y}{x}$, clearly it is not an element of $S$. But $s^2 = \frac{y^2}{x^2} = \frac{x^3}{x^2} = x$ so $s^2 - x = 0$ in $S$, which means $s$ is an $S$-integer.

    ## Exercise 8

    **Let** $$\chi_n = \frac{\sin(n+1)\theta}{\sin(\theta)}, \chi_m = \frac{\sin(m+1)\theta}{\sin(\theta)}$$ **be the characters of the irreducible representations $\varphi_n$ and $\varphi_m$ of $SU(2)$, $m \ge n \ge 1$. Decompose the product $\chi_n\chi_m$ into sum of characters of $SU(2)$. What kind of information is encoded in this decomposition**?

    Solution

    We may write $\chi_n$ and $\chi_m$ as $$\chi_n(z_{\theta}) = e^{in\theta} + e^{i(n-2)\theta} + \dots + e^{-in\theta} = \sum_{k=0}^ne^{i(n-2k)\theta}$$ and similar for $\chi_m(z_{\theta})$. Multiply them together, we get $$\begin{aligned}(\sum_{k=0}^ne^{i(n-2k)\theta})(\sum_{j=0}^me^{i(m-2j)\theta}) &= e^{in\theta}(e^{im\theta} + e^{i(m-2)\theta} + \dots + e^{-im\theta})\\ &+ e^{i(n-2)\theta}(e^{im\theta} + e^{i(m-2)\theta} + \dots + e^{-im\theta})\\ &+ \dots \\ &+e^{-in\theta}(e^{im\theta} + e^{i(m-2)\theta} + \dots + e^{-im\theta}) \\ \\ & = e^{i(n+m)\theta} + e^{i(n+m-2)\theta} + \dots + e^{i(n-m)\theta} \\&+ e^{i(n+m-2)\theta} + e^{i(n+m-4)\theta} + \dots + e^{i(n-m-2)\theta} \\ &+ \dots \\&+e^{i(-n+m)\theta} + e^{i(-n+m-2)\theta} + \dots + e^{i(-n-m)\theta}.\end{aligned}$$ Now look at the equation we get, if we think it as an $n+1$ by $m+1$ table, then each time we move downwards a cell, or rightwards a cell, the coefficients in the exponential function decreased by $2$.

    <img src="public/Pasted image 20220302165337.png" width="600" />

    If we look at the outer-most layer (colored by grey), the coefficients go from $n+m$ all the way to $-n-m$, each time decreased by $2$. Similarly, if we look at the second-outer-most layer, colored by red, the coefficients go from $n+m-2$ to $-n-m+2$, and so on. If $n = m$ then this table is square, and in the end we left with bottom-left corner, which is $e^{i(-n+m)\theta} = e^0 = 1$. More generally if $m\ge n$, we will be left with terms with coefficients go from $-n+m$ to $n-m$ (colored by purple). Group the summands like that, we get: $$\begin{aligned}\chi_n\chi_m &= e^{i(n+m)\theta}+\dots + e^{i(-n-m)\theta}\\&+ e^{i(n+m-2)\theta}+\dots + e^{i(-n-m+2)\theta}\\&+\dots \\&+e^{i(-n+m)\theta}+\dots + e^{i(n-m)\theta}\\&=\chi_{n+m}+\chi_{n+m-2}+\dots+\chi_{-n+m} \\&= \sum_{k=0}^n\chi_{n+m-2k}.\end{aligned}$$ And we get the decomposition.

    Not sure about the information encoded… One thing is that since we know if $U, V$ are some modules and $W = U \otimes V$ is their tensor product, then $\chi_W = \chi_U \chi_V$. From above calculation we will get that the tensor product of the modules correspond to $\chi_m$ and $\chi_n$ is the direct sum of the (simple) modules correspond to $\chi_{n+m}, \chi_{n+m-2}, \dots$, and $\chi_{-n+m}$.
    """
    )
    return


@app.cell
def _(mo):
    mo.md(r"""# Spring Semester Homework 4""")
    return


@app.cell
def _(mo):
    mo.md(
        r"""
    ## Exercise 1

    **Assuming $\mathbb{Z}[\sqrt{-19}]$ contains no non-principal ideals $I$ such that $I^5$ is principal, find all integer solutions of $x^2 + 19 = y^5$**.

    Solution

    Write the equation as $(x - \sqrt{-19})(x+\sqrt{-19}) = y^5$. First we see $x - \sqrt{-19}$ and $x+\sqrt{-19}$ are coprime: if they have a non-trivial common divisor $z$, then $z$ divides their difference $2\sqrt{-19}$, so $z$ is either (divisor of) $2$ or $\sqrt{-19}$. But $2 \nmid x\pm\sqrt{-19}$, so $z = \sqrt{-19}$ so that $x$ is a multiple of $\sqrt{-19}$ so is a multiple of $19$, so $y$ is a multiple of $19$, thus $y^5 - x^2$ should be a multiple of $19^2$ but $19$ is not.

    Thus both $(x - \sqrt{-19})$ and $(x+\sqrt{-19})$ should be $I^5$ for some $I$. By the assumption, $I$ must be principal. So we have $x + \sqrt{-19} = (a + b \sqrt{-19})^5$ for some integers $a, b$. Expand it we get $x = a^5 - 190a^3b^2 + 1805ab^4$ and $1 = b(5a^4-190a^2b^2+361b^4)$. From the second equation we get $b = \pm 1$, so $5a^4 - 190a^2 + 361 = \pm 1$. We can just solve it as a quadratic equation, and it is not very hard to get $a^2 = 36$ thus $a = \pm 6$ are the only integer solutions (in which case $b = 1$). Plugin to the first equation, we get $x = -22434$ if $a = 6$ or $22434$ if $a = -6$. So $y^5 = 22434^2+19$ and we can get $y = 55$.

    So we get two solutions, $x = \pm 22434$ and $y = 55$.

    ## Exercise 2

    **Let $R$ be a noetherian domain with the property that every prime ideal of $R$ is principal. Prove that $R$ is a PID**.

    Proof

    Let $\mathscr{R}$ be the class of all non-principal ideals of $R$ and suppose it is non-empty. Since $R$ is noetherian, $\mathscr{R}$ has a maximal element, let's call it $Q$. By construction $Q$ is not principal, thus by assumption it is not prime. So we can find $x, y \notin Q$ yet $xy \in Q$. So $Q' = Q + (x)$ is larger than $Q$ thus principal. Also consider the ideal quotient $Q:(x)$ $=\lbrace r \in R | r(x) \subseteq Q \rbrace$, we know it is an ideal and apparently it contains $Q$, also we should see $y \in Q:(x)$ because $xy \in Q$, so $Q:(x)$ is also larger than $Q$ thus principal. Say $Q' = (a)$ and $Q:(x) = (b)$. Consider the principal ideal $(ab)$:

    1. $(ab) \subseteq Q$: By construction $(a) = Q+(x)$ so $a$ can be written as $q' + x'$ for some $q' \in Q$ and $x' \in (x)$, so $ab = q'b+x'b$, where $q'b \in Q$ because $Q$ is an ideal, and $x'b \in Q$ by definition of ideal quotient (by saying domain we assume $R$ is commutative ring), thus $ab \in Q$ so $(ab) \subseteq Q$;
    2. $Q \subseteq (ab)$: Let $q \in Q$, by above we know $Q \subset (a)$ so $q = ra$ $=r (q'+x')$ $= rq' + rx'$. Since $rq' \in Q$, we have $rx' = q-rq' \in Q$, thus $r(x) \subseteq Q$, which by definition means $r \in Q:(x) = (b)$, so $r = r'b$, so $q = r'ba \in (ab)$.

    So $Q$ is principal and we have a contradiction, thus there is no non-principal ideal, i.e. $R$ is PID.

    ## Exercise 3

    **Let $R = \mathbb{Z}[\sqrt{-5}]$, and $P = (2, 1 + \sqrt{-5})$ $=(2,1-\sqrt{-5})$, $Q_1 = (3, 1+\sqrt{-5})$, $Q_2 = (3, 1-\sqrt{-5})$ be ideals of $R$**.

    1. **Check that $P,Q_1, Q_2$ are maximal ideals in $R$**;
    2. **Verify that $P^2, PQ_1, PQ_2$ and $Q_1Q_2$ are principal**;
    3. **Check that the factorizations $6 = 2 \cdot 3 = (1+\sqrt{-5})(1-\sqrt{-5})$ lead to the same factorization of $I = (6)$ into prime ideals in $R$**.

    Proof
    1. We know $\mathbb{Z}[\sqrt{-5}] = \lbrace a+b\sqrt{-5}| a, b \in \mathbb{Z} \rbrace$. Consider a map $\varphi: \mathbb{Z}[\sqrt{-5}] \to \mathbb{Z}_2$ given by $a+b\sqrt{-5} \mapsto a+b \pmod{2}$.
        1. It is a homomorphism: Let $a+b\sqrt{-5}$ and $c+d\sqrt{-5}$ be arbitrary elements of $\mathbb{Z}[\sqrt{-5}]$, then $\varphi((a+b\sqrt{-5})(c+d\sqrt{-5}))$ $=\varphi(ac-5bd + (bc+ad)\sqrt{-5})$ $=ac-5bd+bc+ad$ $= ac+bd+bc+ad \pmod{2}$; and $\varphi(a+b\sqrt{-5})\varphi(c+d\sqrt{-5})$ $=(a+b)(c+d) =$ $ac+ad+bc+bd$. So they are the same, $\varphi$ is a homomorphism;
        2. The kernel is $P$: $\varphi(2) = \varphi(1-\sqrt{-5}) = 0$ so $P \subseteq \ker{\varphi}$. If $a+b\sqrt{-5} \in \ker{\varphi}$ then $a+b \equiv 0 \pmod{2}$ $\implies a = -b+2k$, so $a+b\sqrt{-5}$ $= -b+2k+b\sqrt{-5}$ $=2k - b(1-\sqrt{-5})$ $\in P$.
        So $R/P \cong \mathbb{Z}_2$ is a field, $P$ is maximal.
        Similarly, the isomorphism $\mathbb{Z}[\sqrt{-5}] \to \mathbb{Z}_3$ given by $a+b\sqrt{-5} \mapsto a+b$ proves $Q_2$ is maximal, and the isomorphism $\mathbb{Z}[\sqrt{-5}] \to \mathbb{Z}_3$ given by $a+b\sqrt{-5} \mapsto a-b$ proves $Q_1$ is maximal;
    2. A generic element of $P$ is $2a+b(1+\sqrt{-5})$, which can also be written as $2c+d(1-\sqrt{-5})$, so $$P^2 = \lbrace \sum_{i=1}^n (2a_i+b_i(1+\sqrt{-5})(2c_i+d_i(1-\sqrt{-5})) \rbrace.$$ Expand and we can see each summand is of the form $4a_ic_i + 2c_ib_i(1+\sqrt{-5}) + 2a_i d_i(1-\sqrt{-5}) + 6b_i d_i$. In particular each term is a multiple of $2$, so $P^2 \subseteq (2)$. Of course $(2) \subseteq P^2$ so we have $P^2 = (2)$ is principal.
        For $PQ_1$ and $PQ_2$, we should see $P + Q_1$ and $P+Q_2$ are both the entire $R$ because $-2+3 = 1$. So Chinese Remainder Theorem says $PQ_1 = P \cap Q_1$ $=(1+\sqrt{-5})$. To see that: of course $(1+\sqrt{-5}) \subseteq P \cap Q_1$, if $x \in P \cap Q_1$ then $x$ $= 2a + b(1+\sqrt{-5})$ $= 3c + d(1+\sqrt{-5})$ so that $2a + (b-d)(1+\sqrt{-5}) = 3c$, since $3$ is irreducible and $\gcd{(2,3)} = 1$, we need $a$ to be a multiple of $3$ thus $2a$ is a multiple of $6 = (1+\sqrt{-5})(1-\sqrt{-5})$, so that $2a \in (1+\sqrt{-5})$, thus $x \in (1+\sqrt{-5})$. Similarly $PQ_2 = P \cap Q_2$ $= (1-\sqrt{-5})$.
        $Q_1 + Q_2 = R$ as well, because $-(1+\sqrt{-5} + 1 - \sqrt{-5})+3 = 1$. So $Q_1Q_2 = Q_1 \cap Q_2$ $= (3)$;
    3. Maximal ideals are primes, so by part 1 we know $P, Q_1$ and $Q_2$ are prime ideals. Now use part 2, $(6) = (2)(3)$ $= (P^2)(Q_1Q_2)$ is a factorization; and the other one: $(6) = (1+\sqrt{-5})(1-\sqrt{-5})$ $= (PQ_1)(PQ_2)$. Since $R$ is commutative, order of product of ideals does not matter, so the factorizations are the same.

    ## Exercise 4

    **Let $R$ be a domain, $I$ and $J$ be fractional $R$-ideals and $P$ be a prime in $R$. Verify that $I_P + J_P = (I+J)_P$ and $I_PJ_P = (IJ)_P$**.

    Proof

    By definition, $I_P = \lbrace a/b | a \in I, b \in R-P \rbrace$ and $J_P = \lbrace c/d | c \in J, d \in R-P \rbrace$, so $I_P+J_P = \lbrace \frac{a}{b} + \frac{c}{d} = \frac{ad+cb}{bd} | a \in I, c \in J, b,d \in R-P \rbrace$. Consider a generic term $\frac{ad+cb}{bd}$. Since $P$ is prime, $b ,d \notin P \implies bd \notin P$; $ad+cb$ lies in $I+J$ because $a \in I$ and $c \in J$. So $\frac{ad+cb}{bd} \in (I+J)_P$, meaning $I_P+J_P \subseteq (I+J)_P$.

    $(I+J)_P = \lbrace \frac{a+c}{b} | a\in I, c \in J, b\in R-P \rbrace$, clearly we may write any of its element as some $\frac{a}{b} + \frac{c}{b}$ and where $\frac{a}{b}$ lies in $I_P$ and $\frac{c}{d}$ lies in $J_P$, so we have the other inclusion.

    $I_PJ_P = \lbrace \frac{a_1}{b_1}\frac{c_1}{d_1} + \dots + \frac{a_n}{b_n}\frac{c_n}{d_n}| a_i \in I, c_i \in J, b_i, d_i \in R-P\rbrace$. Since $b_1,d_1 \notin P$, a prime ideal, $b_1d_1\notin P$, thus finitely product $b_1d_1\dots b_nd_n \notin P$, combine all fractions and we can see the numerator is in $IJ$. So $I_PJ_P \subseteq (IJ)_P$.

    $(IJ)_P = \lbrace \frac{a_1c_1 + \dots + a_nc_n}{b} | a_i\in I, c_i \in J, b \in R-P\rbrace$, split the fraction to $\sum\frac{a_ic_i}{b}$ where each term can be written as $\frac{a_i}{b} \frac{c_i}{1}$. Since prime ideal is by definition proper, $1 \notin P$, so $\frac{a_i}{b}\in I_P$ and $\frac{c_i}{1} \in J_P$, thus $(IJ)_P \subseteq I_PJ_P$.

    ## Exercise 5

    **Let $F$ be a field and $R = F[[t]]$ be the ring of formal power series over $F$. Show that $R$ is a discrete valuation ring**.

    Proof

    Claim: $f = \sum\limits_{n = 0}^{\infty}a_nt^n$ $\in R$ is a unit if and only if $a_0 \ne 0$.

    ($\implies$) Suppose $f$ is a unit, then we must have some $g = \sum b_nt^n$ so that $fg = 1$, look at the constant term, we must have $a_0b_0 = 1$ so in particular $a_0$ cannot be $0$.

    ($\impliedby$) Suppose $f = \sum\limits_{n = 0}^{\infty}a_nt^n$ with $a_0 \ne 0$, take $g = \sum\limits_{n=0}^{\infty}b_nt^n$ such that $b_0 = \frac{1}{a_0}$, $b_1 = \frac{-a_1b_0}{a_0}$, $\dots$, $b_n = \frac{\sum\limits_{i=1}^n-a_ib_{n-i}}{a_0}$, so that the coefficient of the constant term is $1$, and coefficient of $x^n$ is $0$ for any $n \ge 1$, thus $fg = 1$ and $f$ is a unit.

    In particular, $R - R^{*}$ $=(t)$ is the only maximal ideal, $R$ is local. Any ideal in $R$ can be expressed in the form $(t^n), n \ge 1$ because $f \in R$ are infinite series - just take the smallest power among all terms of the generators (for example, $(2x^3 + 6x^8, x^5)$ is just $(x^3)$). Thus $R$ is a PID. By definition, a local PID is a DVR.

    ## Exercise 6

    **Let $R = \mathbb{Z}[\sqrt{-61}]$ and $I = (2, 3 + \sqrt{-61})$, $J = (5, 3+ \sqrt{-61})$**.

    1. **For each prime $P$ in $R$, find the local generators for $I_P$ and $J_P$**;
    2.**Conclude that $I$ and $J$ are invertible ideals, and determine the order of their classes in $Pic(R)$**.

    Proof

    1. We can see that $R/I \cong \mathbb{Z}_2$ and $R/J \cong \mathbb{Z}_5$, so $I, J$ are both maximal (and prime).
        1. If $P = I$, since $\frac{2}{3+\sqrt{-61}} = \frac{3-\sqrt{-61}}{35}$ and the denominator is not in $I$, $\frac{2}{3+\sqrt{-61}} \in R_I$. In particular, it means $2$ is a multiple of $3+\sqrt{-61}$ in the localization thus is redundant as a generator, we may write $I_I = (3+\sqrt{-61})$ and it is principal;
        2. If $P \ne I$, then there is some non-zero $c \in I$ such that $c \notin P$, then any element in $R_P$, having the form $\frac{a}{b}, a \in R, b \in R-P$ can be written as $\frac{ac}{bc}$ with now $ac \in I$ and $bc \in R-P$ because $P$ is prime, so that we see $R_P \subseteq I_P$. Since $I_P \subseteq R_P$ is immediate from definition, we see now $I_P = R_P$ is the entire ring, and is of course generated by $1$;
        3. If $P = J$, similarly $\frac{5}{3+\sqrt{-61}} = \frac{3-\sqrt{-61}}{14}$ and thus $J_J = (5)$;
        4. If $P \ne J$, similarly $J_P = R_P$ can be generated by $1$;
    2. By part 1, $I_P$ and $J_P$ are principal in $R_P$ for all prime ideals $P \subset R$, and by assumption $I$ and $J$ are finitely generated. By the theorem we learnt in class, we see $I$ and $J$ are invertible.
        Consider $I^2= (4, -52+6\sqrt{-61}, 6+2\sqrt{-61})$, we can see $I^2 = (2)$, thus $I^2 \in \mathcal{P}(R)$, and thus $I$ has order $2$ in the Picard group.
        For $J$ it is a little more complex. Consider the ideals $M = (8+\sqrt{-61})$ and $N = (8-\sqrt{-61})$, it is not hard too see $M+N = R$ since both $16$ and $125$ are in $M+N$ thus $1 \in M+N$. Also $MN = (125) = (5)^3$, we conclude using a lemma learnt in class that $(8+\sqrt{-61}) = (5, 8+\sqrt{-61})^3 = (5,3+\sqrt{-61})^3$, and thus $J^3 \in \mathcal{P}(R)$ and thus $J$ has order $3$ in the Picard group.

    ## Exercise 7

    **Let $\alpha$ be a complex root of $f(X) = X^3 - X - 1$ and $R = \mathbb{Z}[\alpha]$**.

    1. **Write down all prime ideals of norm $\le 25$ in $R$**;
    2. **Verify that the ideals of $R$ lying over $2,3,5,7$ are principal**;
    3. **Verify that the remaining ideals from part 1 are principal as well. You may use Sage to find the generators, e.g. `K.<ALPHA> = NumberField(x^3-x-1);Ideal(23,ALPHA-10)`**.

    Solution
    1. Since $f$ has no roots in $\mathbb{Z}$, it is irreducible, thus by Kummer-Dedekind Theorem, all prime ideals are of the form $(p, g(\alpha))$ where $g$ is a lift of a factor of $f$ in $\mathbb{F}_p[x]$. So let's look into $f$ per $p$:
        1. If $p = 2$, $\overline{f} = x^3-x-1$, so apparently $g(\alpha) = 0$, $P = (2)$ is an ideal of norm $| R/P | = 2^{\deg{f}} = 8$;
        2. If $p = 3$, we similarly get $P = (3)$ and it has norm $27$, not what we want;
        3. If $p = 5$, $\overline{f} = (x+3)(x^2+2x+3)$, so we get two ideals $(5, \alpha+3)$ and $(5, \alpha^2+2x+3)$, they are of norm $5$ and $25$ respectively, because for example $R/(5,\alpha+3) = \lbrace \overline{0},\overline{1},\overline{2},\overline{3},\overline{4}\rbrace$;
        4. If $p = 7$, $\overline{f} = (x+2)(x^2+5x+3)$, similarly we get $(7, \alpha+2)$ of norm $7$ (and $(7, \alpha^2+5\alpha+3)$ of norm $49$, which we don't want);
        5. If $p = 11$, $\overline{f} = (x+5)(x^2+6x+2)$, similarly we get $(11,\alpha+5)$ of norm $11$;
        6. If $p = 13$, $\overline{f} = x^3-x-1$ is irreducible, there is no prime ideal of norm $\le 25$ lying over $13$;
        7. If $p = 17$, $\overline{f} = (x+12)(x^2+5x+7)$, we have $(17, \alpha+12)$ of norm $17$;
        8. If $p = 19$, $\overline{f} = (x+13)(x^2+6x+16)$, we have $(19, \alpha + 13)$ of norm $19$;
        9. And finally, if $p = 23$, $\overline{f} = (x+20)(x+13)^2$, we have two ideals $(23, \alpha + 20)$ and $(23, \alpha+13)$ of norm $23$; For any larger prime $p$, the norm will be of course larger than $25$, so we have finished;
    2. For $p = 2$, the corresponding prime ideal of course principal from above.
        If $p = 5$ we get an ideal $(5,\alpha+3)$ $=(5,\alpha-2)$, notice that $x^3-x-1 = (x^2+2x+3)(x-2) + 5$, but $\alpha^3-\alpha-1 = 0$, so $5 = (-\alpha^2-2\alpha-3)(\alpha-2)$, thus $5$ is redundant as a generator, this is a principal ideal. This expression also shows that $(5, \alpha^2+2\alpha+3) = (\alpha^2+2\alpha+3)$, so it is principal as well.
        If $p = 7$ we get prime ideals $(7,\alpha+2)$ and $(7, \alpha^2-2\alpha+3)$, we can see that they are principal by the expression $x^3-x-1 = (x^2-2x+3)(x+2)-7$, in a similar manner;
    3. Check with Sage, they are indeed all principal, and we finished:
        ```python
        K. = NumberField(x^3-x-1);
        I = Ideal(11, A+5);print(I);
        I = Ideal(17, A+12);print(I);
        I = Ideal(19, A+13);print(I);
        I = Ideal(23, A+20);print(I);
        I = Ideal(23, A+13);print(I);
        >> Fractional ideal (-2*A^2 + A)
        >> Fractional ideal (-A^2 + A + 3)
        >> Fractional ideal (2*A^2 + A - 2)
        >> Fractional ideal (-3*A^2 + A + 1)
        >> Fractional ideal (A^2 - 3*A - 1)
        ```

    ## Exercise 8

    **Determine which of the following rings are Dedekind domains**:

    1. **$\mathbb{Z}[\sqrt[3]{2}]$**,
    2. **$\mathbb{Z}[\sqrt[5]{7}]$**,
    3. **$\mathbb{Z}[\alpha]$ where $\alpha^3 = \alpha+1$**.

    Solution

    1. Consider $f = x^3-2$. If $p = 2$ then $\overline{f} = x^3$ so it is $\overline{g_1}^3$ if $\overline{g_1} = x$, remainder $r_1 = -2 \nmid 4$, so $p = 2$ is regular. If $p = 3$ then $\overline{f} = x^3 + 1 = (x+1)^3$, so it equals $\overline{g_1}^3$ where $g_1 = x+1$, remainder $r_1 = f(-1) = -3 \nmid 9$. Notice $f' = 3x^2$, so the only possible way for $f$ to have double root is when the root is $0$ ($p = 2$) or $f' = 0$ ($p= 3$). Since these two cases are checked, $\mathbb{Z}[\sqrt[3]{2}]$ is Dedekind;
    2. Consider $f = x^5-7$. If $p = 5$ then $\overline{f} = (x+3)^5$, $r_1 = (-3)^5-7 = 250 \equiv 0 \pmod{25}$, so $P_1 = (5, \alpha+3)$ is not invertible, implies $\mathbb{Z}[\sqrt[5]{7}]$ is not Dedekind;
    3. Consider $f = x^3-x-1$, then $f' = 3x^2-1$, $f$ has double root at $x$ only if both $f$ and $f'$ has $x$ as a root, so that $f - \frac{1}{3}xf'$ $= x^3-x-1 - \frac{1}{3}x(3x^2-1)$ $= -\frac{2}{3}x-1 =0$ $\implies x = -\frac{3}{2}$. Since $f'(-\frac{3}{2}) = \frac{23}{4}$, $f$ attains double roots only possibly when $p = 23$ (because only in this case $f'(-\frac{3}{2})$ is actually $0$). If $p = 23$, then $\overline{f} = (x+20)(x+13)^2$, consider $g = (x+13)$, then the corresponding remainder is $f(-13) = -2185 \not\equiv 0 \pmod{23^2}$, thus $p = 23$ is regular, $\mathbb{Z}[\alpha]$ is Dedekind.

    ## Exercise 9

    **Show that the number ring $R$ is a UFD if and only if it is a PID**.

    Proof

    Every PID is UFD, so we only need the other direction.

    Suppose now the number ring $R$ is a UFD, suppose $P$ is a prime ideal of $R$. Suppose $x \in P$. Write $x$ as product of irreducibles, then (at least) one of the irreducible factors is in $P$, say it is $p$. Since $R$ is a UFD, $(p)$ must be a prime ideal (any element in $(p)$ is of the form $rp$, since $p$ is irreducible, at least one of terms in the factorization of $rp$ is in $(p)$). We know in a number ring prime ideals are maximal, so $(p)$ is maximal. But of course $(p) \subseteq P$, since $P$ is by definition proper, we must have $(p) = P$, in particular $P$ is principal. Thus any prime ideal is principal. We also know number ring is noetherian, so by Exercise 2, $R$ is PID.
    """
    )
    return


@app.cell
def _(mo):
    mo.md(r"""# Spring Semester Homework 5""")
    return


@app.cell
def _(mo):
    mo.md(
        r"""
    ## Exercise 1

    **Let $d$ be an integer that is not a cube**.

    1. **Show that $R = \mathbb{Z}[\sqrt[3]{d}]$ is a Dedekind domain if and only if $d$ is square-free and $d \ne \pm 1 \pmod{9}$**;
    2. **Let now $d = p$ be prime, and $d \equiv \pm 1 \pmod{9}$. Determine the singular prime ideals of $R$**.

    Proof

    1. Minimal polynomial of $\sqrt[3]{d}$ is $f(x) = x^3-d = 0$, so $f'(x) = 3x^2$. The possible $p$ that are singular:
        1. $p = 3$, so that $\overline{f'} = 0$. Then $\overline{f} = (x-d)^3$. It is singular if the remainder $=f(d)$ $= d^3-d \equiv 0 \pmod{9}$, we can check that this happens if and only if $d = \pm 1 \pmod{9}$;
        2. $p$ such that $0$ is a double root. It is singular if the remainder $=f(0) = -d \equiv 0\pmod{p^2}$, in particular if $d$ is not square-free.
        Since $R$ is Dedekind if and only if there is no singular $p$, we have the desired result;
    2. By Kummer-Dedekind Theorem, all prime ideals of $R$ is of the form $(q, g_i(\sqrt[3]{d}))$ (using the notation from class, and $q$ is prime integer). So the main task is to find all singular prime, the rest will be straight-forward.
        1. By above we know that $3$ must be a singular prime (given $d \equiv 1 \pmod{9}$), this gives a singular prime ideal $(3, \sqrt[3]{d}-d)$;
        2. From above second case, $q$ is singular (prime) only if $d = p \equiv 0 \pmod{q^2}$, but that is not possible as $p$ is prime.
        So there is only one singular prime ideal $(3, \sqrt[3]{d}-d)$ in $R$.

    ## Exercise 2
    **Let $K = \mathbb{Q}(\alpha)$, where $\alpha^3-3\alpha+9 = 0$, and $R = \mathbb{Z}[\alpha]$**.

    1. **What are the singular primes in $R$? Are there any ramified regular primes**?
    2. **Describe the ring of integers $O_K$. What is $[O_K:R]$**?

    Solution

    1. Denote $f(x) = x^3-3x+9$, then $f' = 3x^2-3$. The possible $p$ that are singular:
        1. $p = 3$, in this case $\overline{f} = x^3$, remainder is $f(0) = 9 \equiv 0 \pmod{9}$ so this is indeed singular;
        2. Otherwise consider $f - \frac{1}{3}xf' = x^3-3x+9-x^3+x = -2x+9$. If $x$ is both root for $f$ and $f'$ (so that it is double root for $f$) then it must be root of $f-\frac{1}{3}xf'$, in particular $x = \frac{9}{2}$ is the only possible double root. Since $f'(\frac{9}{2}) = 231/4$ where $231 = 3 \cdot 7 \cdot 11$, the possible $p$ that really make $\frac{9}{2}$ being a root of $f'$ are $3$, $7$, or $11$. We already see $3$ is singular, so we check the other two:
            1. If $p = 7$ then $\overline{f} = x^3-3x+2$ $=$ $(x+2)(x+6)^2$, $-6$ is a double root, and the remainder $f(-6) = -189 \equiv 7 \pmod{49}$, so $p = 7$ is not singular, it is ramified regular;
            2. If $p = 11$ then $\overline{f} = (x+9)(x+1)^2$, $-1$ is a double root, and remainder $f(-1) = 11 \equiv 11 \pmod{121}$, so $11$ is also a ramified regular.
    2. We saw above that the only singular prime of $R$ is $3$, the corresponding prime ideal is $(3, \alpha)$. Consider $\alpha^3-3\alpha+9 = \alpha\cdot(\alpha^2-3)+9 \implies -\frac{\alpha^2-3}{3} = \frac{3}{\alpha}$, say they equal $\beta$, then $\beta \notin R$ (otherwise $(3,\alpha)$ is principal), then $\frac{3}{\beta} = \alpha \implies (\frac{3}{\beta})^3 - 3(\frac{3}{\beta})+9 = 0$ $\implies \beta^3-\beta^2+3 = 0$. This is an irreducible polynomial (thus is minimal polynomial of $\beta$). We now want to find singular primes in $\mathbb{Z}[\alpha,\beta]$. If $g = x^3-x^2 + 3$ then $g' = 3x^2-2x$.
        Proceed as before, if $g(x) = 0$ and $g'(x) = 0$ then $(g- \frac{x}{3}g')(x) = 0$, which means$(x-3)(x+3) = 0$ thus $x = \pm 3$. In particular $p = 3$ is the only possible singular prime, but since $g(0) = 3 \equiv 3 \pmod{9}$, it is ramified regular. So $\mathbb{Z}[\alpha,\beta]$ is Dedekind so $\mathbb{Z}[\alpha,\beta] \supseteq O_K$. By construction $\beta$ is an algebraic integer, we also have $O_K \supseteq \mathbb{Z}[\alpha,\beta]$, and thus $O_K = \mathbb{Z}[\alpha,\beta]$.
        Basis of $R$ is $\lbrace 1, \alpha, \alpha^2 \rbrace$, and basis of $R' = \mathbb{Z}[\alpha,\beta]$ $= \mathbb{Z}[\alpha, -\frac{\alpha^2-3}{3}]$ is $\lbrace 1, \alpha, -\frac{\alpha^2-3}{3}\rbrace$, so a linear transformation $T: R \to R'$ can be described as $\begin{pmatrix}1&0&1\\0&1&0\\0&0&\frac{1}{3}\end{pmatrix}$, and $[R':R] = | \det{T^{-1}} | = 3$.

    ## Exercise 3

    **Suppose $L = \mathbb{Q}(\alpha)$, and $f$ is the minimal polynomial of $\alpha$ over $\mathbb{Q}$**.

    1. **Verify that $N_{L/\mathbb{Q}}(c-\alpha) = f(c)$ for every $c \in \mathbb{Q}$**;
    2. **Assume now that $p \equiv 1 \pmod{4}$, and prove that $\frac{p^p-1}{p-1}$ is not prime**. *Hint: In one of the homework last semester, we checked that for odd $p$ the cyclotomic field contains an element $\tau$ such that $\tau^2 = \pm p$*.

    Proof

    1. We know $f(c) = f_{L/\mathbb{Q}}^{\alpha}(c)$ for every $c \in \mathbb{Q}$, which by definition equals $\det(c\cdot \text{id}_L - M_{\alpha})$ which is exactly $\det(M_{c-\alpha})$ (because for any $y \in L$, $(c\cdot \text{id}_L - M_{\alpha})(y) = cy-\alpha y = (c-\alpha)(y) = M_{c-\alpha}(y)$) which is by definition $N_{L/\mathbb{Q}}(c-\alpha)$;
    2. Consider $\alpha = e^{2\pi i/p}$ so that $L = Q_p$ is the $p$-th cyclotomic field.
        1. Suppose $p\equiv 1 \pmod{4}$ but $p$ is not prime. Then we know from last semester that $x^p-1 = \prod\limits_{d| p}\Phi_d(x)$ $=(x-1)\prod\limits_{d| p, d \ne 1}\Phi_d(x)$ thus $\frac{x^p-1}{x-1} =\prod_{d | p, d\ne 1}\Phi_d(x)$ where $\Phi_d(x) \in \mathbb{Z}[x]$. Since $p$ is assumed not to be prime, it has at least $2$ factors that is not $1$, so $\frac{x^p-1}{x-1}$ is product of at least two $\Phi_d(x)$. Plugin $x = p$ we get that $\frac{p^p-1}{p-1}$ has at least two factors (they are clearly distinct and not $1$) so it is not prime;
        2. Otherwise $p \equiv 1 \pmod{4}$ and $p$ is prime. From homework in last semester we know that there is some $\tau \in \mathbb{Q}_p$ such that $\tau^2 = p$. Since $p$ is prime, $f = \frac{x^p-1}{x-1}$ is minimal polynomial for both $\alpha$ and $\alpha^2$. So by part 1, we get $N_{L/\mathbb{Q}}(p-\alpha) = f(p)$ and $N_{L/\mathbb{Q}}(p-\alpha^2) = f(p)$, so $$N_{L/\mathbb{Q}}(p-\alpha) = N_{L/\mathbb{Q}}((\tau+\alpha)(\tau-\alpha)) = N_{L/\mathbb{Q}}(\tau+\alpha)N_{L/\mathbb{Q}}(\tau-\alpha).$$ Since $\tau$ (and $\alpha$, of course) is in $O_L$, we have both $N_{L/\mathbb{Q}}(\tau+\alpha),N_{L/\mathbb{Q}}(\tau-\alpha)$ are integers. We have the desired statement if they are both not $1$:
        3. If $N_{L/\mathbb{Q}}(\tau-\alpha) = 1$, then $\frac{\tau^p-1}{\tau-1} = 1 \implies \tau^p = \tau$ $\implies \tau^{p-1} = 1$ which cannot be true;
        4. If $N_{L/\mathbb{Q}}(\tau+\alpha) = 1$ then $N_{L/\mathbb{Q}}(\tau-\alpha) = (\frac{\tau^p-1}{\tau-1})/1 = \frac{\tau^p-1}{\tau-1}$ $\implies$ $\tau^{p-1} = 1$ again.

        So they are both not $1$ and we get the desired statement.

    ## Exercise 4

    **Compute the class group $\text{Cl}(L)$, where**:

    1. **$L = \mathbb{Q}(\sqrt{-71})$**;
    2. **$L = \mathbb{Q}(\sqrt{-65})$**.

    Solution

    1. $-71 \equiv 1 \pmod{4}$, so $O_L = \mathbb{Z}[\frac{1+\sqrt{-71}}{2} = \alpha]$. Minimal polynomial of $\alpha$ is $f(x) = x^2-x+18$. Take $c \in \mathbb{Z}$, $N(c-\alpha)$ $= f(c)$. In particular we can calculate: $$\begin{array}{|r|r|}\hline c&f(c) = N(c-\alpha) \\ \hline -1&2^2\cdot5\\\hline 0&2\cdot 3^2\\\hline 1&2\cdot 3^2\\\hline 2&2^2\cdot 5\\\hline 3&2^3\cdot 3\\\hline\end{array}$$

        1. If $p = 2$, then $\overline{f} = x(x-1)$, $(2) = P_2Q_2$ where $P_2 = (2,\alpha)$, $Q_2 = (2, \alpha-1)$;
        2. If $p = 3$, then $\overline{f} = x(x-1)$, $(3)$ $= P_3Q_3$ where $P_3 = (3,\alpha)$, $Q_3 = (3, \alpha-1)$;
        3. If $p = 5$, then $\overline{f} = (x+1)(x+3)$, $(7) = P_7Q_7$ where $P_5 = (5,\alpha+1)$, $Q_5 = (5,\alpha+3)$.

        In the class group, $[P_2] = -[Q_2]$, $[P_3] = -[Q_3]$ and $[P_5] = -[Q_5]$. Read the table we also have:

        1. $(-1-\alpha) = Q_2^2P_5$ thus $2[Q_2] = -[P_5]$;
        2. $(\alpha) = P_2P_3^2$ thus $[P_2] = -2[P_3]$;
        3. $(3-\alpha) = Q_2^3P_3$.

        If we set $[P_3] = \eta \in \text{Cl}(L)$, then we get $[P_2] = -2\eta$ and $[P_5]= -4\eta$, also from 3. We get $7\eta = 0$. Thus a reasonable guess would be $\text{Cl}(L) \cong \mathbb{Z}_7 = \langle \eta \rangle$. We need to check if $P_3$ is principal. If $P_3 = (3,\alpha) = (\delta)$, then $N_{L/\mathbb{Q}}(\delta) = \delta\overline{\delta} = 3$, but for $\delta \in \mathbb{Z}[\frac{1+\sqrt{-71}}{2}]$ this is not possible. So $\text{Cl}(L) \cong \mathbb{Z}_7$.
    2. $-65 \equiv 3 \pmod{4}$, so $O_L = \mathbb{Z}[\sqrt{-65}]$, corresponding minimal polynomial is $f = x^2 + 65$. We can calculate $M_R = \frac{2}{\pi}\sqrt{260}$ $\approx 10$ so we need to look over $p = 2,3,5,7$:
        1. $p = 2$, then $\overline{f} = (x+1)^2$, $(2) = P_2^2$ where $P_2 = (2, \alpha+1)$, $2[P_2] = 0$;
        2. $p = 3$, then $\overline{f} = (x+1)(x+2)$, $(3) = P_3Q_3$ where $P_3 = (3,\alpha+1)$, $Q_3= (3, \alpha+2)$, $[P_3] = -[Q_3]$;
        3. $p = 5$, then $\overline{f} = x^2$, $(5) = P_5^2$ where $P_5 = (5,\alpha)$, $2[P_5] = 0$;
        4. $p = 7$, then $\overline{f} = x^2+2$ is inert.

        Consider $\beta = 5- \alpha$, then $N(\beta) = f(5) = 90 = 2\cdot 3^2 \cdot 5$, so $(5-\alpha) = P_2P_3^2P_5$ in particular $[P_2P_5] = -2[P_3]$. $P_2P_5$ cannot be principal, because we can calculate that there is no ideal of norm $10$.
        Consider $\gamma = 4-\alpha$, then $N(\gamma) = f(4)$ $= 81 = 3^4$, so $4[P_3] = 0$, $[P_3]$ is of order $4$.
        Also $[P_2] \ne -[P_3]$, otherwise $P_2P_3$ is principal but there is no ideal of norm $6$. So we can use $[P_2]$ and $[P_3]$ as generator, we get $\text{Cl}(L) = \mathbb{Z}_2 \times \mathbb{Z}_4$.

    ## Exercise 5

    **Let $0 \to K \to P \xrightarrow{\varphi} M \to 0$ and $0 \to K' \to P' \xrightarrow{\varphi'} M \to 0$ be two exact sequences of $R$-modules with $P$, $P'$ both projective. Prove that $P \oplus K' \cong P' \oplus K$ as $R$-modules**. *Hint: consider the module given by the condition $\varphi(p) = \varphi'(p')$*.

    Proof

    Consider the sub-module $N \subset P \oplus P'$ by $N = \lbrace (p, p') | \varphi(p) = \varphi'(p') \rbrace$. Claim, for each $p \in P$, there exists $p' \in P'$ so that $(p,p')$ is in $N$, and vice versa. This is easy: for any given $p$, let $\varphi(p) = m$, since $\varphi'$ in surjective, we can find $p'$ so that $\varphi'(p') = m$ so $\varphi'(p') = \varphi(p)$.

    Now consider map $\alpha: N \to P$ given by $(p,p') \to p$. By above discussion, this map is surjective. Thus by a proposition from class, this map splits, where $$\begin{aligned}\ker{\alpha} &= \lbrace (p,p') | p = 0,\varphi(p) = \varphi'(p')\rbrace \\ &=\lbrace (0,p') | \varphi'(p') = 0\rbrace \\& \cong \ker{\varphi'}\end{aligned}$$ which is isomorphic to $K'$ because $0 \to K' \to P' \xrightarrow{\varphi'} M \to 0$ is assumed to be a short exact sequence. In particular, we get that $$0 \xrightarrow{} K' \xrightarrow{} N \xrightarrow{\alpha} P \xrightarrow{} 0$$ is a split short exact sequence, thus $N \cong P \oplus K'$.

    Now do the same thing with the map $\beta: N \to P'$ given by $(p,p') \to p'$, and we get $N \cong P' \oplus K$, put things together we have $P' \oplus K \cong P \oplus K'$.
    """
    )
    return


if __name__ == "__main__":
    app.run()
